### ISSUE TITLE
How to use CircleCI's 'no_output_timeout' property

### ISSUE THREAD

**Issue by thathurtabit** [cypress-io/circleci-orb#125]
My Cypress tests somtimes run longer than the default `10m`. This leads to a failure.

Circle CI provides a `no_output_timeout` step, i.e.. `no_output_timeout: 30m` to increase the timeout to 30 mins, but I'm not sure how to get this to work with this circleci-orb.

See: [CircleCi Steps config](https://circleci.com/docs/2.0/configuration-reference/#steps)

As a workaround, you may be able to use the [fully resolved configuration](https://github.com/cypress-io/circleci-orb#effective-config) and add the `no_output_timeout` setting, i.e.:

```
version: 2

orbs:
  cypress: cypress-io/cypress@1
#   Fully resolved config below

jobs:
  cypress/run:
    docker:
      - image: cypress/base:10
    parallelism: 1
    steps:
      - checkout
      - restore_cache:
          keys:
            - cache-{{ .Branch }}-{{ checksum "package.json" }}
      - run:
          name: Npm CI
          command: npm ci
      - run:
          command: npx cypress verify
      - save_cache:
          key: cache-{{ .Branch }}-{{ checksum "package.json" }}
          paths:
            - ~/.npm
            - ~/.cache
      - persist_to_workspace:
          root: ~/
          paths:
            - project
            - .cache/Cypress
      - attach_workspace:
          at: ~/
      - run:
          name: Run local server
          command: npm start
          background: true
      - run:
          name: Run Cypress tests
          command: npx cypress run
          no_output_timeout: 25m

  build:
    docker:
      - image: circleci/node:10.12.0-stretch
    working_directory: ~/repo
    steps:
         ... build steps

workflows:
  build:
    jobs:
      - cypress/run
      - build:
          requires:
            - cypress/run
  version: 2

```
