### ISSUE TITLE
CI Error: "Cannot find a definition for command named cypress/run"

### ISSUE THREAD

**Issue by amkoehler** [cypress-io/circleci-orb#131]
Hi, I'm having an odd issue when trying to use this orb. Here's my config:

```yml
version: 2.1
orbs:
  cypress: 'cypress-io/cypress@1'
jobs:
  test:
    docker:
      - image: circleci/node:8-browsers
    steps:
      - checkout
      - run:
          name: Authenticate with npm registry
          command: echo "//registry.npmjs.org/:_authToken=$NPM_TOKEN" > ~/.npmrc
      # Cache to enable faster future jobs
      - run: npm install
      - save_cache:
          paths:
            - node_modules
          key: v1-dependencies-{{ checksum "package.json" }}
      # Run unit tests
      - run: npm run test
      # Run integration tests
      - cypress/run
workflows: 
  test_and_deploy:
    jobs: 
      - test
```

With this config the build fails immediately with the error "Cannot find a definition for command named cypress/run". I thought there was some sort of issue with the orb installation, but I can replace `cypress/run` with `cypress/install` and that command runs just fine. Any ideas? This feels like something painfully obvious but I'm not sure where to look next.

**Comment by amkoehler** [comment]
Argh, this can be chalked up as user error. I was trying to run this as a step within a job, when it should have been a separate job in my `test_and_deploy` workflow. Working great now.

**Comment by bahmutov** [comment]
yup, there is no "run" command in this Orb - there is "install", but "run" is the name of the job. 

![Screen Shot 2019-06-17 at 4 04 15 PM](https://user-images.githubusercontent.com/2212006/59633032-9914d500-9119-11e9-8dce-5434d129dc5d.png)

Looking at your config file, you just need npmrc token, which you can do simpler by following this example: https://github.com/cypress-io/circleci-orb/blob/master/docs/examples.md#install-private-npm-modules

**Comment by amkoehler** [comment]
@bahmutov perfect timing, I was just about to go looking for how to configure the npm auth. Thanks!

**Comment by Buuntu** [comment]
> yup, there is no "run" command in this Orb - there is "install", but "run" is the name of the job.
> 
> ![Screen Shot 2019-06-17 at 4 04 15 PM](https://user-images.githubusercontent.com/2212006/59633032-9914d500-9119-11e9-8dce-5434d129dc5d.png)
> 
> Looking at your config file, you just need npmrc token, which you can do simpler by following this example: https://github.com/cypress-io/circleci-orb/blob/master/docs/examples.md#install-private-npm-modules

I'm still getting this issue when trying to define a series of commands within a job.  So should the above example look like this since there is no "cypress/run" command?

```yaml
version: 2.1
orbs:
  cypress: 'cypress-io/cypress@1'
jobs:
  test:
    docker:
      - image: circleci/node:8-browsers
    steps:
      - checkout
      - run:
          name: Authenticate with npm registry
          command: echo "//registry.npmjs.org/:_authToken=$NPM_TOKEN" > ~/.npmrc
      # Cache to enable faster future jobs
      - run: npm install
      - save_cache:
          paths:
            - node_modules
          key: v1-dependencies-{{ checksum "package.json" }}
      # Run unit tests
      - run: npm run test
      # Run integration tests
      - run:
         command: "cypress" // change to this?
workflows: 
  test_and_deploy:
    jobs: 
      - test
```
