### ISSUE TITLE
cache-key throws Build Error in CircleCI

### ISSUE THREAD

**Issue by hibearpanda** [cypress-io/circleci-orb#152]
When using yarn and setting cache-key, CircleCI will throw the following Build Error:

<img width="717" alt="Screenshot 2019-07-23 at 6 43 11 PM" src="https://user-images.githubusercontent.com/11482515/61706168-fc79ce80-ad79-11e9-9c1d-03bd08c035d9.png">

The relevant section of my config.yml looks like this:
```
workflows:
  integration_test:
    jobs:
      - cypress/run:
          name: integration_test
          yarn: true
          cache-key: 'yarn-packages-{{ arch }}-{{ checksum "yarn.lock" }}'
          build: 'yarn build-cypress'
          start: 'yarn start-cypress'
          wait-on: 'http://localhost:3000'
          filters:
            branches:
              ignore: master
            tags:
              ignore: /^release-.*/
```

I've also tried removing the name param like so:
```
workflows:
  integration_test:
    jobs:
      - cypress/run:
          yarn: true
          cache-key: 'yarn-packages-{{ arch }}-{{ checksum "yarn.lock" }}'
          build: 'yarn build-cypress'
          start: 'yarn start-cypress'
          wait-on: 'http://localhost:3000'
          filters:
            branches:
              ignore: master
            tags:
              ignore: /^release-.*/
```
