### ISSUE TITLE
Add ability to cache by npm-shrinkwrap.json instead of package-lock.json

### ISSUE THREAD

**Issue by lifeiscontent** [cypress-io/circleci-orb#153]
## The orb does not work as expected

- what version of the orb are you currently using? latest
  * maybe the problem has been fixed already, check the orb releases at [cypress-io/circleci-orb/releases](https://github.com/cypress-io/circleci-orb/releases)
- paste the `circle.yml` file if possible or at least the relevant portion

```yml
version: 2.1
orbs:
  cypress: cypress-io/cypress@1.8.0
executors:
  default:
    node: 10.16.0
workflows:
  build:
    steps:
      - checkout
      - restore_cache:
          keys:
            - << parameters.cache-key >>
      - run: npm ci
      - save_cache:
          key: << parameters.cache-key >>
          paths:
            - ~/.npm
            - ~/.cache
    jobs:
      - cypress/install:
          build: NO_SOURCE_MAPS=true npm run build
      - cypress/run:
          cache-key: cache-{{ arch }}-{{ .Branch }}-{{ checksum "npm-shrinkwrap.json" }}
          requires:
            - cypress/install
          group: 'ci tests'
          record: true
          spec: cypress/integration/circle_ci/*
          start: npm start
          store_artifacts: true
          wait-on: 'http-get://localhost:3000'
          post-steps:
            - store_test_results:
                path: cypress/results
```

- describe what you think should happen
should allow npm-shrinkwrap.json NOT only package-lock.json
- describe what happens
  * screenshots and links to the CircleCI builds would be great
