### ISSUE TITLE
Allow multiple cache keys

### ISSUE THREAD

**Issue by bbugh** [cypress-io/circleci-orb#157]
We are exploring this orb for a Rails and Vue app. `bundle` for gems can take quite a while since we have some native gems that require a build process. Unfortunately, with this orb, there does not seem to be any way to use the bundler cache that we produce as part of our workflow.

I imagine the feature would look like this:

```yaml
workflows:
  build:
    jobs:
      - cypress/run:
          yarn: true
          cache-keys: 
            - 'yarn-packages-{{ arch }}-{{ checksum "yarn.lock" }}'
            - 'bundler-{{ arch }}-{{ checksum "Gemfile.lock" }}'
```
