### ISSUE TITLE
Job: `cypress/install` doesn't accept `custom-cache-key` as documented.

### ISSUE THREAD

**Issue by derekclair** [cypress-io/circleci-orb#162]
## The orb does not work as expected

- what version of the orb are you currently using? `cypress-io/cypress@1.8.0`
  * maybe the problem has been fixed already, check the orb releases at [cypress-io/circleci-orb/releases](https://github.com/cypress-io/circleci-orb/releases)
- paste the `circle.yml` file if possible or at least the relevant portion
```yaml
  deploy:
    jobs:
      - cypress/install:
          cache_key: v1-cypress-{{ arch }}-{{ .Branch }}-{{ checksum "web/yarn.lock" }}
          # --- or ---
          cache_key: v1-cypress-{{ arch }}-{{ .Branch }}-{{ checksum "web/yarn.lock" }}
          # --- or ---
          # w/o either
![Screen Shot 2019-08-16 at 10 18 08 AM](https://user-images.githubusercontent.com/5247629/63182259-613de700-c00f-11e9-9005-5c82f5c15d3c.png)

          working_directory: web/
          yarn: true
      - cypress/run:
          requires:
            - cypress/install
          cache-key: v1-cypress-{{ arch }}-{{ .Branch }}-{{ checksum "web/yarn.lock" }}
          no-workspace: true
          store_artifacts: true
          yarn: true
          working_directory: web/

```
- describe what you think should happen
As is described in the [docs](https://circleci.com/orbs/registry/orb/cypress-io/cypress) "Usage Examples", under the "custom-cache-key" heading, the value passed to the Job is used. 

> Apply custom key for npm install **(or yarn install)** cache. Useful to tweak caching settings to your liking. Related options "yarn".
```yaml
version: 2.1
orbs:
  cypress: cypress-io/cypress@1
workflows:
  build:
    jobs:
      - cypress/run:
          yarn: true
          cache-key: 'yarn-packages-{{ arch }}-{{ checksum "yarn.lock" }}'
```

Albeit _that_ example is running the `cypress/run` Job, the `install` Job _does_ state:

> Checks out code, installs dependencies, attaches code to the workspace for the future jobs
to use **(usually `cypress/run` follows the install step).**

We are currently a monorepo, which means that when the `cypress/install` Job is ran, which in-turn invokes the `install` Command, which then invokes the `setup` Command. the `restore_cache` Step is not relative to the `working_directory`; which, in the case of a monorepo, means there is no `package.json` to checksum for the cache key.
- describe what happens
  * screenshots and links to the CircleCI builds would be great

With `cache_key`
![Screen Shot 2019-08-16 at 9 44 18 AM](https://user-images.githubusercontent.com/5247629/63180159-e7a3fa00-c00a-11e9-9d76-496fa51793cc.png)

With `cache-key`
![Screen Shot 2019-08-16 at 9 43 57 AM](https://user-images.githubusercontent.com/5247629/63182439-d0b3d680-c00f-11e9-972f-fbebf9089d66.png)

Without
![Screen Shot 2019-08-16 at 10 20 06 AM](https://user-images.githubusercontent.com/5247629/63182280-70249980-c00f-11e9-9825-6f0e6dd63b00.png)

**Comment by derekclair** [comment]
While I suppose it is possible to do something along the lines of
```yaml
commands:
  setup:
    ...
    parameters:
      cache-key:
        default: 'cache-{{ arch }}-{{ .Branch }}-{{ checksum "<< parameters.working_directory >>/package.json" }}'
```

I wouldn't think that to be the _right_ solution. (I'm preparing a PR with what I believe to be the right solution. Standby.)
