### ISSUE TITLE
Can't define resource_class and branches

### ISSUE THREAD

**Issue by ArielGueta** [cypress-io/circleci-orb#172]
Hey,

According to the official docs we should be able to define the [resource_class](https://circleci.com/docs/2.0/configuration-reference/#resource_class) and branches keys within a job. But when trying to do it using this orb I get the following error:

```
# Error calling workflow: 'build'
# Error calling job: 'cypress/run'
# Unexpected argument(s): resource_class, only
# 
# -------
# Warning: This configuration was auto-generated to show you the message above.
# Don't rerun this job. Rerunning will have no effect.
false
```

Here is the yml file:

```yml
version: 2.1
orbs:
  cypress: cypress-io/cypress@1
workflows:
  build:
    jobs:
      - cypress/run:
          command: npm run e2e:ci
          working_directory: client
          resource_class: xlarge
          branches:
            only:
              - feature/cypress

```

**Comment by bahmutov** [comment]
Yeah, I see that CircleCI orbs do not inherit the built-in job parameters like `resource_class` or `branches`. I think it would be simpler to pass `resource_class` from the job to the executor, or you could just point at your own custom executor with `resource_class`.

For the `branches` - I don't see a way to actually pass this as a setting via a job, which looks like an oversight on CircleCI part. Maybe open an issue at https://github.com/circleci/circleci-docs with this question?

**Comment by ArielGueta** [comment]
Thanks for the response. I will open a question in their repo. In the meantime can you show an example for:

> I think it would be simpler to pass resource_class from the job to the executor, or you could just point at your own custom executor with resource_class.

I'm not a CircliCi expert, and it will be helpful. Thanks in advance.

**Comment by bahmutov** [comment]
Certainly - here is how you would define your own executor and use it for `cypress/run` job https://github.com/cypress-io/circleci-orb/blob/master/docs/examples.md#custom-executor and in your case you would just set `resource_class` on that executor.

**Comment by ArielGueta** [comment]
```yml
version: 2.1
orbs:
  cypress: cypress-io/cypress@1
executors:
  custom:
    resource_class: xlarge
workflows:
  build:
    jobs:
      - cypress/run:
          executor: custom
          command: npm run e2e:ci
          working_directory: client
```

And it will inherit the defaults from the orb?

**Comment by bahmutov** [comment]
No, you have to describe all executor properties yourself

**Comment by jennifer-shehane** [comment]
Closing as this is not implemented as possible via CircleCI orb currently.

**Comment by OndeVai** [comment]
Why has this been closed? It still does not work...

**Comment by jcity** [comment]
@OndeVai if you want to use a custom executor or resource class you have to define your own job and the the commands separately - can do it like this:

```yml
version: 2.1

orbs:
  # https://circleci.com/developer/orbs/orb/cypress-io/cypress?version=3.1.1
  cypress: cypress-io/cypress@3.1.1
  
 jobs:
  run-cypress-tests:
    # you can use a different executor or resource_class here
    executor: cypress/default
    resource_class: xlarge
    steps:
      - checkout 
      - cypress/install
      - cypress/run-tests
  
workflows:
  version: 2
  test-build-image:
    jobs:
      - run-cypress-tests
```
