### ISSUE TITLE
Error calling install command for cypress/run

### ISSUE THREAD

**Issue by chipit24** [cypress-io/circleci-orb#178]
I'm getting the following error in CircleCI for all my branches, without having made any changes to my CircleCI config:

> Config Processing Error (Don't rerun)
> ```
> #!/bin/sh -eo pipefail
> # Error calling workflow: 'build'
> # Error calling job: 'cypress/run'
> # Error calling command: 'install'
> # Type error for argument build: expected type: steps, actual value: \"\" (type string)
> # 
> # -------
> # Warning: This configuration was auto-generated to show you the message above.
> # Don't rerun this job. Rerunning will have no effect.
> false
> Exited with code 1
> ```

I was using version 1.7.0 of the orb but upgraded it to 1.10.0; I'm still having the same problem. Here is my `circle.yml` config:

```yml
version: 2.1
orbs:
  cypress: cypress-io/cypress@1.10.0
executors:
  with-chrome:
    docker:
      - image: 'cypress/browsers:node10.16.0-chrome76'
workflows:
  build:
    jobs:
      - cypress/run:
          executor: with-chrome
          browser: chrome
          command: 'npm run lint && npm run test-ci'
          post-steps:
            - store_artifacts:
                path: coverage
```

Usually, the build passes, and I see all the following steps executed successfully:
<img width="417" alt="Screen Shot 2019-09-18 at 12 19 16 PM" src="https://user-images.githubusercontent.com/7561061/65166376-a38f8500-da0e-11e9-9488-5ba8082a24b7.png">

But now I'm see this (described above):
<img width="754" alt="Screen Shot 2019-09-18 at 12 20 19 PM" src="https://user-images.githubusercontent.com/7561061/65166412-b1dda100-da0e-11e9-8f8e-7397d2cfc2cd.png">

**Comment by alessbell** [comment]
+1, I also started seeing this error this morning running orb `cypress-io/cypress@1`.

**Comment by davemason-ladbible** [comment]
+1 also seeing this running 1.8.0

**Comment by dannyrb** [comment]
Same issue. Open source, so here's the build + config: https://circleci.com/gh/OHIF/Viewers/3327

**Comment by chipit24** [comment]
It seems if I replace my custom executer to use one of their predefined ones, things work:

```yml
version: 2.1
orbs:
  cypress: cypress-io/cypress@1.10.0
workflows:
  build:
    jobs:
      - cypress/run:
          executor: cypress/browsers-chrome76
          browser: chrome
          command: 'npm run lint && npm run test-ci'
          post-steps:
            - store_artifacts:
                path: coverage

```

Notice I've replaced `executor: with-chrome` with `executor: cypress/browsers-chrome76`, and removed my `executors` config.
