### ISSUE TITLE
How can I fix tofu font?

### ISSUE THREAD

**Issue by yousan** [cypress-io/circleci-orb#200]
# The orb does not work as expected

- what version of the orb are you currently using?
`cypress: cypress-io/cypress@1`

- describe what happens

![image](https://user-images.githubusercontent.com/561613/68363243-928d0580-016d-11ea-8fa3-fbf545982ab9.png)

- paste the `circle.yml` file if possible or at least the relevant portion

```
  cypressrun: # E2E
    docker:
      - image: cypress/base:10
    parallelism: 1
    steps:
      - checkout
      - restore_cache:
          keys:
            - cache-{{ arch }}-{{ .Branch }}-{{ checksum "package.json" }}
      - run:
          name: Check if package-lock.json exists
          command: |
            if [ ! -e ./package-lock.json ]; then
              echo "The Cypress orb uses 'npm ci' to install 'node_modules', which requires a 'package-lock.json'."
              echo "A 'package-lock.json' file was not found. Please run 'npm install' in your project,"
              echo "and commit 'package-lock.json' to your repo."
              exit 1
            fi
          working_directory: ''
      - run:
          name: Npm CI
          command: npm ci
          working_directory: ''
      - run:
          name: Verify Cypress
          command: npx cypress verify
          working_directory: ''
      - save_cache:
          key: cache-{{ arch }}-{{ .Branch }}-{{ checksum "package.json" }}
          paths:
            - ~/.npm
            - ~/.cache
      - run:
          command: ./bin/cypress.sh
          working_directory: ''
      - store_artifacts:
          path: cypress/videos
      - store_artifacts:
          path: cypress/screenshots
      - store_test_results:
          path: cypress/results
```

- describe what you think should happen
No tofu font
