### ISSUE TITLE
Add a flag for running debug

### ISSUE THREAD

**Issue by paulfalgout** [cypress-io/circleci-orb#203]
Unless I'm mistaken the only way to implement `DEBUG=cypress*` for debugging cypress issues on ci is to modify the command at which point, I have to manually also add all of the various parallel, group, etc flags?

It'd be nice if this was `debug: true`

**Comment by bahmutov** [comment]
Right now the way to pass additional environment variables is to make a custom executor https://github.com/cypress-io/circleci-orb/blob/master/docs/examples.md#env-vars which is a lot of work, I agree. A better way could probably be passing env var like this https://circleci.com/docs/2.0/reusing-config/#environment-variable-name

```yml
version: 2.1
jobs:
   # dummy job name
   cypress-run:
     parameters:
       debug:
         type: env_var_name
         default: DEBUG
     docker:
       - image: ubuntu:latest
     steps:
       - run: |
           DEBUG=${<< parameters.debug >>} \\
           npx cypress run ...
workflows:
  workflow:
    jobs:
      - cypress-run
```
