### ISSUE TITLE
cypress verify

### ISSUE THREAD

**Issue by imkarmadev** [cypress-io/circleci-orb#220]
## The orb does not work as expected

- what version of the orb are you currently using? cypress-io/cypress@1.13.0
- paste the `circle.yml` file if possible or at least the relevant portion
```yaml
version: 2.1
orbs:
  cypress: cypress-io/cypress@1.13.0
workflows:
  version: 2
  mainline:
    jobs:
      - cypress/run:
          yarn: true

```
- describe what happens
```
#!/bin/bash -eo pipefail
npx cypress verify

internal/modules/cjs/loader.js:582
    throw err;
    ^

Error: Cannot find module '/root/.npm/_npx/116/lib/node_modules/cypress/index.js'
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:580:15)
    at Function.Module._load (internal/modules/cjs/loader.js:506:25)
    at Function.Module.runMain (internal/modules/cjs/loader.js:741:12)
    at startup (internal/bootstrap/node.js:285:19)
    at bootstrapNodeJSCore (internal/bootstrap/node.js:739:3)
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! cypress@3.8.3 postinstall: `node index.js --exec install`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the cypress@3.8.3 postinstall script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /root/.npm/_logs/2020-02-03T11_44_58_888Z-debug.log
Install for cypress@latest failed with code 1

Exited with code exit status 1

```
