### ISSUE TITLE
Verify Cypress step failing due to Odd Cache Directory Location

### ISSUE THREAD

**Issue by basicdays** [cypress-io/circleci-orb#223]
## The orb does not work as expected

- what version of the orb are you currently using?
1.14

- paste the `circle.yml` file if possible or at least the relevant portion

```yaml
executors:
  with-e2e-dev:
    docker:
      - image: cypress/browsers:node11.13.0-chrome73
    working_directory: /app
    environment: 'OMITTED'

workflows:
  version: 2
  jobs:
    e2e-tests:
      - cypress/run:
          name: run-e2e-tests-dev
          command: 'OMITTED'
          context: 'OMITTED'
          yarn: true
          executor: with-e2e-dev
```

- describe what you think should happen
  I have now pinned the Orb to version 1.13 since it started to fail on 1.14. The Verify Cypress step is failing to find the installed Cypress version.

- describe what happens
  The Verify Cypress step is failing with the following result:

![Screen Shot 2020-02-10 at 15 36 34](https://user-images.githubusercontent.com/124954/74192496-4396b680-4c1b-11ea-91ea-b5bfecbcc337.png)
