### ISSUE TITLE
Allow custom workspace path

### ISSUE THREAD

**Issue by kylemh** [cypress-io/circleci-orb#233]
The workspace path is hard-coded as `'~/'`, but I may define my workspace path if I'm moving files all around the `/tmp` for example.

**Comment by jcuffney** [comment]
Not sure if this is related... but I am not able to install and it seems like that's because the install is happening at `/root/project` as opposed to `/home/circleci/project`

This is the config:

```yaml
- cypress/install:
          context: GITHUB
          pre-steps:
            - run: echo "//npm.pkg.github.com/:_authToken=\"$GITHUB_ACCESS_TOKEN\"" >> .npmrc
          build: npm run build
```

and this is the output when cypress/install runs:

`Directory (/root/project) you are trying to checkout to is not empty and not a git repository`
