### ISSUE TITLE
Create e2e tests in orb 

### ISSUE THREAD

**Issue by kylemh** [cypress-io/circleci-orb#240]
As mentioned in #148, before shipping breaking changes, Gleb wants to see some e2e tests so that we're more certain of changes going out.

I imagine this looks like having a simple web-app with a test job per example?

**Comment by bahmutov** [comment]
Probably will need multiple full examples that actually will use the orb for real, otherwise things like #242 will get through

**Comment by bahmutov** [comment]
Maybe we can snapshot generated example effective configs in addition to just checking their syntax.

**Comment by kylemh** [comment]
In some respect, it might be easier to accomplish full coverage of all possible examples if we ship a breaking change first which simplifies the possible options.

It would mean fewer combinations of possibilities to cover. For example, if we eliminate the `yarn` prop entirely in favor of `install-command` with a default of `npm ci`.

Thoughts on that?

I'm sure there's a way that we can run all of the [other examples](https://github.com/cypress-io/circleci-orb#other-examples) as actual YAML and just run it as part of CI in this repo against... idk... maybe create-react-app. Does that sound good to start? I'd love to get on that for ya.

**Comment by bahmutov** [comment]
Probably can do it as subfolders in this repo - not every combination should be tested, but a few main ones. Probably using https://circleci.com/orbs/registry/orb/circleci/orb-tools#jobs-test-in-builds

```yml
version: 2.1
orbs:
  orb-tools: circleci/orb-tools@9.0.1
workflows:
  orb_tests:
    jobs:
      - orb-tools/test-in-builds:
          checkout: true
          orb-location: src/orb.yml
          orb-name: 'cypress-io/cypress'
          test-steps:
            - cypress/run:
                ...?
```
Not sure, the Circle's docs really have zero examples
