### ISSUE TITLE
Yarn dependencies no longer automatically installing

### ISSUE THREAD

**Issue by editkid** [cypress-io/circleci-orb#242]
## The orb does not work as expected

v1.19.0

About ~13hrs ago ( around `2020-03-11T18:00:18.739Z`) our tests stopped automatically running `yarn install`: we ended up without a `node_modules` folder. Previously this was happening automatically.

The solution/workaround was to use the new custom `install-command`, but I assume that shouldn't be required?

**Orb version**
v1.18.0

**circle.yml**
```
      - cypress/run:
          executor: cypress
          yarn: true
          working_directory: cypress
```

**Our workaround**
```
      - cypress/run:
          executor: cypress
          working_directory: cypress
          install-command: yarn install --frozen-lockfile
```
Thank you. :v:
