### ISSUE TITLE
Use no_output_timeout parameter on build.

### ISSUE THREAD

**Issue by LeopoldBriand** [cypress-io/circleci-orb#246]
Using : cypress-io/cypress@1
config.yml : 

```yml
version: 2.1
orbs:
  cypress: cypress-io/cypress@1
executors:
  with-chrome:
    docker:
      - image: 'cypress/browsers:chrome69'
    resource_class: medium
    environment:
      NODE_OPTIONS: --max_old_space_size=4096
workflows:
  build:
    jobs:
      - cypress/install:
          executor: with-chrome
          build: npm run circleci:build
      - cypress/run:
          requires:
            - cypress/install
          start: npm serve:dist
          wait-on: 'http://localhost:8080'
          executor: with-chrome
          config-file: cypress.dist.env.json
          browser: chrome
          record: true
          post-steps:
            - store_artifacts:
                path: /tmp/artifacts
```
I would have liked to use the no_output_timeout parameter on the build run, is it possible and how?
Despite my research, I haven't been able to change this setting.
