### ISSUE TITLE
Can not define the branches for the job to execute

### ISSUE THREAD

**Issue by 31186** [cypress-io/circleci-orb#261]
Hello there. I am configuring Circleci to be used with cypress for the first time, but I can not get the job to execute only for the master branch.
I'm using the cypress orb and added the branches config from the Circleci documentation, but for some reason, these configs are being ignored when running the job.
Do the branch configs need to be added in the orb in order to work?

```
version: 2.1
orbs:
  cypress: cypress-io/cypress@1
workflows:
  build:
    jobs:
      - cypress/run:
          name: "Cypress E2e Tests"
          executor: cypress/browsers-chrome69
          browser: chrome
          store_artifacts: true
build:
  branches:
    only:
      - master
```
