### ISSUE TITLE
circle-ci run test error

### ISSUE THREAD

**Issue by LeopoldBriand** [cypress-io/circleci-orb#264]
## The orb does not work as expected

orb version : 1.19.2
./circleci/config.yml:
```yml
version: 2.1
orbs:
  cypress: cypress-io/cypress@1.19.2
executors:
  with-chrome:
    docker:
      - image: 'cypress/browsers:node10.16.3-chrome80-ff73'
    resource_class: medium
    environment:
      NODE_OPTIONS: --max_old_space_size=4096
workflows:
  build:
    jobs:
      - cypress/install:
          executor: with-chrome
          pre-steps:
            - run: 'echo "//registry.npmjs.org/:_authToken=${NPM_TOKEN}" >> ~/.npmrc'
      - cypress/run:
          requires:
            - cypress/install
          start: npm start
          wait-on: '-c .circleci/wait-on-config.json http-get://localhost:8080'
          config-file: .circleci/cypress.json
          executor: with-chrome
          browser: chrome
          record: false
          post-steps:
            - store_artifacts:
                path: /tmp/artifacts
```
.circleci/cypress.json:
```json
{
    "integrationFolder": "test/e2e/cypress/integration",
    "fixturesFolder": "test/e2e/cypress/fixtures/",
    "supportFile": "test/e2e/cypress/support/index.js",
    "pluginsFile": "test/e2e/cypress/plugins/",
    "projectId": "yqxyet",
    "viewportWidth": 1200,
    "viewportHeight": 800,
    "env": {
        "baseUrl": "http://localhost:8080/",
        "screenshotsOnRunFailure": true,
        "screenshotsFolder": "/tmp/artifacts/cypress/screenshots/",
        "video": false,
        "videosFolder": "/tmp/artifacts/videos/"
    }
}
```
I think it has something to do with :
https://github.com/cypress-io/cypress/issues/6213 
because we used monaco-editor

screenshot of circleci build: 
![error](https://user-images.githubusercontent.com/53423281/79871613-e2dae580-83e4-11ea-92e7-979a726197f7.png)
all test pass on my computer that use node v10 and chrome80 but not on circle-ci

Thanks a lot for reading, best regards.
