### ISSUE TITLE
store_artifacts does not work with working_directory

### ISSUE THREAD

**Issue by bahmutov** [cypress-io/circleci-orb#265]
in a repo like this
```
root/
  tests/
    e2e/
      cypress.json
```

If we run tests using working directory pointing at `tests/e2e` then `store_artifacts` still points at the root

```
cypress/run:
  working_directory: tests/e2e
  store_artifacts: true

Uploading /root/cypress/videos to cypress/videos
  No artifact files found at /root/cypress/videos
```

**Comment by bahmutov** [comment]
This is when we have separate install job, and the run job does
```
- cypress/run:
    attach-workspace: true
    requires:
      - cypress/installk
    build: npm run build
```
we assume only the install job does the build in this case (which is wrong)
