### ISSUE TITLE
build command is skipped when attaching workspace

### ISSUE THREAD

**Issue by bahmutov** [cypress-io/circleci-orb#266]
```
workflows:
  build:
    jobs:
      - cypress/run:
          attach-workspace: true
          build: npm run build
```

The `build` command is not in effective config
