### ISSUE TITLE
Cache failure due to root user in job.

### ISSUE THREAD

**Issue by KyleTryon** [cypress-io/circleci-orb#269]
## The orb does not work as expected

- what version of the orb are you currently using?
    cypress-io/cypress@1.19.2

The cypress/run job can not currently utilize the saving and loading cache feature as the cache is saved to `* /root/.cache` and does not have permission to pull the cache from there.

I noticed the cache path is set statically:
https://github.com/cypress-io/circleci-orb/blob/master/src/orb.yml#L192

Error when restoring cache:

```
Found a cache from build 116 at yarn-packages-arch1-linux-amd64-6_85-0GqtS35ErNtuJWhFvT+JIP6xECcpEyLwDVOB3dtUgLc=
Size: 150 MiB
Cached paths:
  * /root/.cache

Downloading cache archive...
Validating cache...

Unarchiving cache...

Failed to unarchive cache

Error untarring cache: Error extracting tarball /tmp/xxxxx: tar: root/.cache: Cannot mkdir: Permission denied tar: root/.cache/Cypress: Cannot mkdir: Permission denied tar: root/.cache/Cypress/4.4.0: Cannot mkdir: Permission denied tar: root/.cache/Cypress/4.4.0/Cypress: Cannot mkdir: Permission denied tar: root/.cache/Cypress/4.4.0/Cypress/Cypress: Cannot open: Permission denied tar: root/.cache/Cypress/4.4.0/Cypress/LICENSE.electron.txt: Cannot open: Permission denied tar: root/.cache/Cypress/4.4.0/Cypress/LICENSES.chromium.html: Cannot open: Permission denied tar: root/.cache/Cypress/4.4.0/Cypress/chrome-sandbox: Cannot open: Permission denied tar: root/.cache/Cypress/4.4.0/Cypress/chrome_100_percent.pak: Cannot open: Permission denied tar: root/.cache/Cypress/4.4.0/Cypress/chrome_200_percent.pak: Cannot open: Permission denied tar: root/.cache/Cypress/4.4.0/Cypress/crashpad_handler: Cannot open: Permission denied tar: root/.cache/Cypress/4.4.0/Cypress/icudtl.dat: Cannot open: Permission denied tar: root/.cache/Cypress/4.4.0/Cypress/libEGL.so: Cannot open: Permissi: exit status 2
```

**Comment by pui** [comment]
This issue is keeping me from integrating cypress into my circleci build. It would be great if this could be addressed soon.

**Comment by bahmutov** [comment]
Since we are using Yarn and Orb this cannot be it (maybe you are using some specific image or container?)

Our example that uses Yarn is in https://github.com/cypress-io/cypress-example-todomvc-redux and the CircleCI jobs in https://app.circleci.com/pipelines/github/cypress-io/cypress-example-todomvc-redux?branch=master

**Comment by pui** [comment]
FYI I'm a little new to both circleci and cypress.

I'm trying to run cypress against my rails application. I'm using a ruby docker image and I think that is the problem:

```
version: 2.1
orbs:
  cypress: cypress-io/cypress@1
executors:
  with-ruby:
    # use an image with Node and Ruby and browser dependencies
    # https://circleci.com/docs/2.0/circleci-images/
    docker:
      - image: circleci/ruby:2.6.4-node-browsers
workflows:
  build:
    jobs:
      - cypress/run:
          # install Ruby dependencies
          build: bundle install
          start: ls && rails server
          wait-on: 'http://localhost:3000'
          executor: with-ruby
          yarn: true
          cache-key: 'yarn-packages-{{ arch }}-{{ checksum "yarn.lock" }}'
```
