### ISSUE TITLE
Need ability to have start parameter take more than one command

### ISSUE THREAD

**Issue by desi** [cypress-io/circleci-orb#270]
Our project has a frontend server and backend server (api). We use a mock api for the backend in cypress tests. We need to be able to run the mock server (to mimic backend api) and a front end server in Circle CI. 

Below is what I have tried but it isn't working so I am trying to figure out what I need to do to start that second server specifically on circleci
```
- cypress/run:
     executor: cypress/base-12-14-0
     yarn: true
     start: yarn start && yarn start-mockapi
```

I asked about this in the gitter chat and was directed to open a ticket as the start parameter likely doesn't handle passing both commands.
