### ISSUE TITLE
Can't verify Cypress

### ISSUE THREAD

**Issue by eclecsis** [cypress-io/circleci-orb#277]
## The orb does not work as expected

- what version of the orb are you currently using?
1.21.0
- paste the `circle.yml` file if possible or at least the relevant portion
```
version: 2.1
orbs:
  cypress: cypress-io/cypress@1
workflows:
  build:
    jobs:
      - cypress/run:
          yarn: true
          working_directory: ~/folder/secondfolder/correctfolder
```
- describe what you think should happen
"Verify Cypress" step should pass on CircleCI.

We are new to Cypress and trying to use the orb to get very basic tests to run on CI. We're starting with the simplest configuration possible, just to get it up and running. Yet it's failing CI at "Verify Cypress."

When I run either `npx cypress verify` or `yarn cypress verify` within the project locally, Cypress verifies. I can, of course, run the project's Cypress tests locally so it seems to be installed correctly. Cypress is included under devDependencies in the package.json for the directory that I've specified as the working directory (the project is a monorepo, so I only want Cypress to run on the front-end directory; the monorepo structure sometimes causes issues so perhaps this is part of the problem). I can't figure out why it's not verifying on CI.

I'm guessing this has a simple fix since it seems like an installation or directory problem, but nothing I do is fixing it.

- describe what happens
The 'Verify Cypress' CI step fails with `Error: Cannot find module '/root/.npm/_npx/80/lib/node_modules/cypress/index.js'`
![image](https://user-images.githubusercontent.com/20763036/81550666-e0830000-9380-11ea-9407-db6f434b25ac.png)
