### ISSUE TITLE
cypress/run: working_directory not used when storing artifacts

### ISSUE THREAD

**Issue by mkorpela** [cypress-io/circleci-orb#278]
## The orb does not work as expected

- what version of the orb are you currently using?
cypress-io/cypress@1.21.0
  * maybe the problem has been fixed already, check the orb releases at [cypress-io/circleci-orb/releases](https://github.com/cypress-io/circleci-orb/releases)
- paste the `circle.yml` file if possible or at least the relevant portion
cypress/run:

```
    cypress/run:
          command: yarn cypress run --env MODE=staging
          yarn: true
          working_directory: frontend
          store_artifacts: true
          cache-key: 'cache-{{ arch }}-{{ checksum "frontend/package.json" }}'
          requires:
            - deploy-staging
          filters:
            branches:
              ignore:
                - master
```
- describe what you think should happen
Should store artifact videos from frontend/cypress/videos
```
Finished processing: /root/project/frontend/cypress/videos/myfunny.spec.js.mp4     (1 second)
```
- describe what happens
working_directory is not really used as I expect.
```
Uploading /root/project/cypress/videos to cypress/videos
  No artifact files found at /root/project/cypress/videos
```

**Comment by mkorpela** [comment]
My command until someone fixes this:
`command: CYPRESS_videosFolder=../cypress/videos yarn cypress run --env MODE=staging`

**Comment by bahmutov** [comment]
Can you show the resolved config for this job please?

https://github.com/cypress-io/circleci-orb#effective-config

There was a fix for store artifacts with custom working directory in https://github.com/cypress-io/circleci-orb/releases/tag/v1.19.2 and there is a test for this 

- https://github.com/cypress-io/circleci-orb/blob/master/manual-tests/store-artifacts.test.ts
- https://github.com/cypress-io/circleci-orb/blob/master/manual-tests/store-artifacts.test.ts.md

**Comment by mkorpela** [comment]
It’s not a problem for me anymore thus I’m not going to invest more time on this.
I’ve reported the problem on the level of detail I assume to be enough for reproducing the problem. Thus ”needs more info” seems like ignorance.

**Comment by mkorpela** [comment]
Ok blaah you win :(

```
  cypress/run:
    docker:
    - image: cypress/base:10
    parallelism: 1
    environment:
    - CYPRESS_CACHE_FOLDER: ~/.cache/Cypress
    steps:
    - run:
        command: echo "Assuming dependencies were installed using cypress/install job"
    - attach_workspace:
        at: ~/
    - checkout
    - restore_cache:
        keys:
        - cache-{{ arch }}-{{ checksum "frontend/package.json" }}
    - run:
        name: Install
        working_directory: frontend
        command: "if [[ ! -z \"\" ]]; then\n  echo \"Installing using custom command\"\n  echo \"\"\n  \nelif [ \"true\" = \"true\" ]; then\n  echo \"Installing using Yarn\"\n  yarn install --frozen-lockfile\nelif [ ! -e ./package-lock.json ]; then\n  echo \"The Cypress orb uses 'npm ci' to install 'node_modules', which requires a 'package-lock.json'.\"\n  echo \"A 'package-lock.json' file was not found. Please run 'npm install' in your project,\"\n  echo \"and commit 'package-lock.json' to your repo.\"\n  exit 1\nelse\n  echo \"Installing dependencies using NPM ci\"\n  npm ci\nfi\n"
    - run:
        name: Verify Cypress
        command: npx cypress verify
        working_directory: frontend
    - save_cache:
        key: cache-{{ arch }}-{{ checksum "frontend/package.json" }}
        paths:
        - ~/.cache
    - persist_to_workspace:
        root: ~/
        paths:
        - project
        - .cache/Cypress
    - run:
        name: Run Cypress tests using custom command
        command: yarn cypress run --env MODE=staging
        no_output_timeout: 10m
        working_directory: frontend
    - store_artifacts:
        path: cypress/videos
        working_directory: frontend
    - store_artifacts:
        path: cypress/screenshots
        working_directory: frontend
```
