### ISSUE TITLE
How to use yarn to install dependencies

### ISSUE THREAD

**Issue by bahmutov** [cypress-io/circleci-orb#28]
What if the user wants to use `yarn` to install dependencies instead of `npm ci`?

**Comment by arielger** [comment]
Also, it would be great to provide an option to use `npm install` instead of `npm ci` for users not commiting the `package-lock.json` file.
Thanks for this orb 🙌

**Comment by bahmutov** [comment]
agree @arielger I should expose this as a job argument and pass it to the install command, if you want to take a look how to do this and do a PR, that would speed things up :)

**Comment by bahmutov** [comment]
also need to think how to config caching then. 
- current install uses `npm ci` and caches `~/.npm` folder
- if using `yarn install` do we want to cache just `~/.cache` folder? It is cached already for Cypress
- if using `npm install` should we cache `node_modules` folder?

**Comment by bahmutov** [comment]
I think a good idea here is to use an `enum` parameter to limit ourselves to just `npm ci`, `npm install` and `yarn install` to avoid complexity. Also this would make possible to configure cached folders automatically - which would make the correct configuration easy by default, which is my number one wish for the orb. For now I don't see how to run commands based on `enum` value though, so I have opened an issue https://github.com/CircleCI-Public/config-preview-sdk/issues/128

**Comment by bahmutov** [comment]
They have suggested using bash shell logic to implement conditions, like 
```yaml
version: 2.1
jobs:
  example:
    docker:
      - image: node/node:10
    parameters:
      foo:
        description: Foo enum
        type: 'enum'
        enum: ['a', 'b', 'c']
        default: 'a'
    steps:
      - run:
          command: |
            if ["<< parameters.foo >>" == "a"]; echo 'foo is a'
      - run:
          command: |
            if ["<< parameters.foo >>" == "b"]; echo 'foo is b'
      - run:
          command: |
            if ["<< parameters.foo >>" == "c"]; echo 'foo is c'

workflows:
  build:
    jobs:
      - example:
          foo: 'b'
```
which becomes config file after resolving with command `circleci config process example.yml | sed /^#/d`

```yaml
version: 2
jobs:
  example:
    docker:
    - image: node/node:10
    steps:
    - run:
        command: |
          if ["b" == "a"]; echo 'foo is a'
    - run:
        command: |
          if ["b" == "b"]; echo 'foo is b'
    - run:
        command: |
          if ["b" == "c"]; echo 'foo is c'
workflows:
  build:
    jobs:
    - example
  version: 2
```

**Comment by bahmutov** [comment]
Blocked until I can figure out how to modify `paths` in `save_cache` list based on command parameters https://github.com/CircleCI-Public/config-preview-sdk/issues/128#issuecomment-441398930

```yaml
- save_cache:
    key: cache-{{ .Branch }}-{{ checksum "package.json" }}
    paths:
      - ~/.npm
      - ~/.cache
```
