### ISSUE TITLE
Add command-prefix parameter

### ISSUE THREAD

**Issue by amirrustam** [cypress-io/circleci-orb#283]
## Objective
Add a new `command-prefix` parameter to allow users to wrap cypress execution or do something else prior to running cypress. This parameter would provide an alternative use case over `command` parameter which would require the user pass in all cypress args/flags directly via the command, and ignore Orb's cypress parameters.

### Example Usecase
- Run cypress with Percy
```yaml
      - cypress/run:
          name: "UI Tests - Chrome"
          browser: chrome
          spec: cypress/tests/ui/*
          executor: with-chrome-and-firefox
          wait-on: "http://localhost:3000"
          command-prefix: npx percy exec -- 
          yarn: true
          start: yarn start:ci
          record: true
          parallel: true
          parallelism: 5
          group: "UI - Chrome"
```
