### ISSUE TITLE
cypress/run always attaches a workspace

### ISSUE THREAD

**Issue by maalur** [cypress-io/circleci-orb#293]
## cypress/run always attaches a workspace

- using orb version 1.24.0, circleci version 2.1
- relevant source code:
  https://github.com/cypress-io/circleci-orb/blob/v1.24.0/src/orb.yml#L518-L526
```
      - when:
          condition: << parameters.parallel >> << parameters.attach-workspace >>
          # user wants to run in parallel mode
          # thus we assume the dependencies were installed as separate job
          # hmm, can we detect if this job requires cypress/install automatically?
          steps:
            - run: echo "Assuming dependencies were installed using cypress/install job"
            - attach_workspace:
                at: ~/
```
- what I think should happen:
  A workspace should only be attached when `parameters.parallel` or `parameters.attach-workspace` are set to `true`.
- what happens:
  The current `condition` always evaluates to true, even when both `parameters.parallel` and `parameters.attach-workspace` are explicitly set to `false`. This results in a workspace always being attached. This can add a significant amount of time to job execution when loading large workspaces.
- proposed solution:
  Based on CircleCI's [Logic Statements documentation](https://circleci.com/docs/2.0/configuration-reference/#logic-statements) I believe this should solve the issue:
```
      - when:
          condition:
            or: [ << parameters.parallel >>, << parameters.attach-workspace >> ]
          # user wants to run in parallel mode
          # thus we assume the dependencies were installed as separate job
          # hmm, can we detect if this job requires cypress/install automatically?
          steps:
            - run: echo "Assuming dependencies were installed using cypress/install job"
            - attach_workspace:
                at: ~/
```
