### ISSUE TITLE
Percy: Error: Failed to launch the browser process! spawn /root/project/node_modules/puppeteer/.local-chromium/linux-756035/chrome-linux/chrome ENOENT 

### ISSUE THREAD

**Issue by ryota-murakami** [cypress-io/circleci-orb#294]
## The orb does not work as expected

- what version of the orb are you currently using?
cypress-io/cypress@1.24.0

- paste the `circle.yml` file if possible or at least the relevant portion

```yml
version: 2.1
orbs:
    cypress: cypress-io/cypress@1.24.0
jobs:
    typecheck:
        docker:
            - image: circleci/node:13.14.0
        parallelism: 1
        working_directory: ~/repo
        steps:
            - checkout
            - run: yarn install
            - run: yarn typecheck
    build:
        docker:
            - image: circleci/node:13.14.0
        working_directory: ~/repo
        parallelism: 1
        steps:
            - checkout
            - run: yarn install
            - run: yarn build
    test:
        docker:
            - image: circleci/node:13.14.0
        working_directory: ~/repo
        parallelism: 1
        steps:
            - checkout
            - run: yarn install
            - run: yarn test
    lint:
        docker:
            - image: circleci/node:13.14.0
        working_directory: ~/repo
        parallelism: 1
        steps:
            - checkout
            - run: yarn install
            - run: yarn lint
workflows:
    create-react-app-typescript-todo-example-2020:
        jobs:
            - typecheck
            - build
            - test
            - lint
            - cypress/install:
                  yarn: true
                  executor: cypress/base-14
            - cypress/run:
                  requires:
                      - cypress/install
                  yarn: true
                  command-prefix: npx percy exec --
                  executor: cypress/browsers-chrome78-ff70
                  browser: chrome
                  record: false     # record results on Cypress Dashboard
                  parallel: true      # split all specs across machines
                  parallelism: 1      # use 4 CircleCI machines to finish quickly
                  group: 'all tests'  # name this group "all tests" on the dashboard
                  start: 'yarn start'  # start server before running tests
```

- describe what you think should happen
Might be executor `cypress/browsers-chrome78-ff70` image cause launch failed puppeteer.
I got relevant issue searched with error massage.
https://github.com/puppeteer/puppeteer/issues/3994

- describe what happens
`Error: Failed to launch the browser process! spawn /root/project/node_modules/puppeteer/.local-chromium/linux-756035/chrome-linux/chrome ENOENT` rising when executed `npx percy exec --`

#### CircleCI LInk
https://app.circleci.com/pipelines/github/laststance/create-react-app-typescript-todo-example-2020/772/workflows/6768bd4d-659a-4e68-834a-69f34b602ab9/jobs/4592/parallel-runs/0/steps/0-104

#### Entire Steps
https://app.circleci.com/pipelines/github/laststance/create-react-app-typescript-todo-example-2020/772/workflows/6768bd4d-659a-4e68-834a-69f34b602ab9/jobs/4592/steps
