### ISSUE TITLE
cypress/base-12 seems to require libgbm-dev

### ISSUE THREAD

**Issue by bitjson** [cypress-io/circleci-orb#299]
## The orb does not work as expected

- what version of the orb are you currently using?
  * `cypress-io/cypress@1.25.0`
- paste the `circle.yml` file if possible or at least the relevant portion

```yml
version: 2.1
orbs:
  cypress: cypress-io/cypress@1.25.0
workflows:
  build:
    jobs:
      - cypress/run:
          executor: cypress/base-12
          command-prefix: npx percy exec --
          yarn: true
          start: yarn start
          wait-on: 'http://localhost:3000'
          no-workspace: true
          record: true
          store_artifacts: true
          post-steps:
            - run: yarn test:unit
            - store_artifacts:
                path: coverage
```

- describe what happens

```
[percy] created build #6: https://percy.io/8bced43b/bitauth-ide/builds/6192058
    Error: Failed to launch the browser process!
    /root/project/node_modules/puppeteer/.local-chromium/linux-756035/chrome-l
    inux/chrome: error while loading shared libraries: libgbm.so.1: cannot 
    open shared object file: No such file or directory
```

[Failed build](https://app.circleci.com/pipelines/github/bitauth/bitauth-ide/7/workflows/b03a040b-c911-4046-a01f-331a6ffe1a2d/jobs/9)

The problem seems [easy to resolve](https://github.com/puppeteer/puppeteer/issues/5661#issuecomment-614814537) – the `libgbm-dev` package needs to be installed. 

Workaround ([successful build](https://app.circleci.com/pipelines/github/bitauth/bitauth-ide/jobs/14)):
```yml
[...]
      - cypress/run:
          post-install:
            - run: apt-get update
            - run: apt-get install -y libgbm-dev
[...]
```
