### ISSUE TITLE
ci-build-id does not receive/evaluate CIRCLE_SHA1 value

### ISSUE THREAD

**Issue by kevinold** [cypress-io/circleci-orb#300]
## The orb does not work as expected

- what version of the orb are you currently using?
  1.25.0
- paste the `circle.yml` file if possible or at least the relevant portion

Complete config here:
https://github.com/cypress-io/cypress-realworld-app/pull/436/files#diff-1d37e48f9ceff6d8030570cd36286a61

```
- cypress/run:
          name: "UI Tests - Chrome"
          browser: chrome
          spec: cypress/tests/ui/*
          executor: with-chrome-and-firefox
          wait-on: "http://localhost:3000"
          yarn: true
          start: yarn start:ci
          record: true
          parallel: true
          parallelism: 5
          ci-build-id: $CIRCLE_SHA1
          group: "UI - Chrome"
          requires:
            - Setup Linux
          post-steps:
            - report-coverage
```

All iterations on this PR: https://github.com/cypress-io/cypress-realworld-app/pull/436

- describe what you think should happen

  - The $CIRCLE_SHA1 environment variable **value** should be passed as the value to `ci-build-id` value to the Cypress Circle Orb
OR

  - The Cypress Circle Orb should evaluate/interpret the string passed to it

- describe what happens

https://app.circleci.com/pipelines/github/cypress-io/cypress-realworld-app/1485/workflows/51430cb2-af17-4918-9ac4-f9f1206161a1/jobs/5441

Failing builds with the following:

Failing builds show '$CIRCLE_SHA1' as the value passed to Cypress via the --ci-build-id flag
![Screen Shot 2020-07-22 at 3 53 07 PM](https://user-images.githubusercontent.com/21967/88228375-b6797400-cc34-11ea-9ebe-1b5d802c52c3.png)

This is reflected in the Cypress Dashboard and this prior run over a month ago with the uniq ci-build-id of $CIRCLE_SHA1 is failing this build:

https://dashboard.cypress.io/projects/7s5okt/runs/1625/specs
![Screen Shot 2020-07-22 at 3 49 43 PM](https://user-images.githubusercontent.com/21967/88228476-d6a93300-cc34-11ea-9b9f-46500a675bab.png)
