### ISSUE TITLE
Customize paths to cache

### ISSUE THREAD

**Issue by alex289** [cypress-io/circleci-orb#310]
## Add own paths to the cache

I'm using the cypress orb to test my Nextjs application. 
A build is required to run the app so it would make it faster to cache the created build (and restore it).
In my case it is `.next/cache`.

**Comment by bahmutov** [comment]
Ohhh this is an interesting idea, definitely worth exploring. Could it be done using some kind of post install command right now though?

**Comment by JuzouSatoru2** [comment]
I tried the following circleci config:

```yml
version: 2.1
orbs:
  cypress: cypress-io/cypress@1.26.0
workflows:
  build:
    jobs:
      - cypress/install:
          build: 'npm run build'
          pre-steps:
            - restore_cache:
              keys:
                - v2-build-{{ checksum "package.json" }}
              paths:
                - .next/cache
          post-steps:
            - save_cache:
              keys:
                - v2-build-{{ checksum "package.json" }}
      - cypress/run:
          requires:
            - cypress/install
          start: npm run start
          wait-on: 'http://localhost:3000'
          store_artifacts: true
          parallel: true
          parallelism: 4
          group: 'all tests'
          no-workspace: true

```

The result of this is following error:

```
ERROR IN CONFIG FILE:

[#/jobs/cypress~1install] only 1 subschema matches out of 2

1. [#/jobs/cypress~01install/steps] 6 schema violations found

|   1. [#/jobs/cypress~001install/steps/0] 0 subschemas matched instead of one

|   |   1. [#/jobs/cypress~0001install/steps/0] 3 schema violations found

|   |   |   1. [#/jobs/cypress~00001install/steps/0] extraneous key [keys] is not permitted

|   |   |   |   Permitted keys:

|   |   |   |     - persist_to_workspace

|   |   |   |     - save_cache

|   |   |   |     - run

|   |   |   |     - checkout

|   |   |   |     - attach_workspace

|   |   |   |     - store_test_results

|   |   |   |     - restore_cache

|   |   |   |     - store_artifacts

|   |   |   |     - add_ssh_keys

|   |   |   |     - deploy

|   |   |   |     - setup_remote_docker

|   |   |   |   Passed keys:

|   |   |   |     []

|   |   |   2. [#/jobs/cypress~00001install/steps/0] extraneous key [paths] is not permitted

|   |   |   |   Permitted keys:

|   |   |   |     - persist_to_workspace

|   |   |   |     - save_cache

|   |   |   |     - run

|   |   |   |     - checkout

|   |   |   |     - attach_workspace

|   |   |   |     - store_test_results

|   |   |   |     - restore_cache

|   |   |   |     - store_artifacts

|   |   |   |     - add_ssh_keys

|   |   |   |     - deploy

|   |   |   |     - setup_remote_docker

|   |   |   |   Passed keys:

|   |   |   |     []

|   |   |   3. [#/jobs/cypress~00001install/steps/0] maximum size: [1], found: [2]

|   |   |   |   SCHEMA:

|   |   |   |     maxProperties: 1

|   |   |   |   INPUT:

|   |   |   |     null

|   |   2. [#/jobs/cypress~0001install/steps/0] Input not a valid enum value

|   |   |   Steps without arguments can be called as strings

|   |   |     enum:

|   |   |     - checkout

|   |   |     - setup_remote_docker

|   |   |     - add_ssh_keys

|   2. [#/jobs/cypress~001install/steps/8] 0 subschemas matched instead of one

|   |   1. [#/jobs/cypress~0001install/steps/8] extraneous key [keys] is not permitted

|   |   |   Permitted keys:

|   |   |     - persist_to_workspace

|   |   |     - save_cache

|   |   |     - run

|   |   |     - checkout

|   |   |     - attach_workspace

|   |   |     - store_test_results

|   |   |     - restore_cache

|   |   |     - store_artifacts

|   |   |     - add_ssh_keys

|   |   |     - deploy

|   |   |     - setup_remote_docker

|   |   |   Passed keys:

|   |   |     []

|   |   2. [#/jobs/cypress~0001install/steps/8] Input not a valid enum value

|   |   |   Steps without arguments can be called as strings

|   |   |     enum:

|   |   |     - checkout

|   |   |     - setup_remote_docker

|   |   |     - add_ssh_keys
```

**Comment by JuzouSatoru2** [comment]
Oh I realized I kinda forgot whitespaces. I'll investigate this.

**Comment by JuzouSatoru2** [comment]
Okey, so now it is working, but nothing will be cached because the build command is executed after the post step `save_cache`.

**Comment by kylemh** [comment]
Where the recommendation comes from:
https://github.com/vercel/next.js/blob/master/errors/no-cache.md

My current CircleCI Config:
```
version: 2.1

orbs:
  cypress: cypress-io/cypress@1

executors:
  default:
    resource_class: large
    docker:
      - image: cypress/base:14.10.1 # keep in sync with .nvmrc and any other executors

parameters:
  workspace_root:
    type: string
    default: '~/'
  primary_cache_key:
    type: string
    default: 'air/next-{{ .Branch }}-{{ checksum "yarn.lock" }}'
  backup_cache_key:
    type: string
    default: 'air/next-{{ .Branch }}-'
  org_level_cache_key:
    type: string
    default: 'air/next-'

exclude_main: &exclude_main
  filters:
    branches:
      ignore: main

aliases:
  - &attach_workspace
    attach_workspace:
      at: << pipeline.parameters.workspace_root >>

  - &restore_cache
    restore_cache:
      keys:
        - << pipeline.parameters.primary_cache_key >>
        # Fallback in case checksum fails.
        - << pipeline.parameters.backup_cache_key >>
        - << pipeline.parameters.org_level_cache_key >>
  - &yarn_install
    run:
      name: 'Installing dependencies...'
      command: yarn install --non-interactive --frozen-lockfile --cache_folder << pipeline.parameters.workspace_root >>.cache/yarn

  - &create_npmrc
    run:
      name: 'Create .npmrc to set NPM_TOKEN...'
      command: echo "//registry.npmjs.org/:_authToken=${NPM_TOKEN}" > ~/.npmrc

jobs:
  install_dependencies:
    executor: default
    steps:
      - checkout
      - *attach_workspace
      - *create_npmrc
      - *restore_cache
      - *yarn_install
      - run: node --version
      - run: yarn --version
      - save_cache:
          key: << pipeline.parameters.primary_cache_key >>
          paths:
            - node_modules
            - << pipeline.parameters.workspace_root >>.cache/yarn
            - << pipeline.parameters.workspace_root >>.cache/Cypress

workflows:
  ci:
    jobs:
      - install_dependencies:
          <<: *exclude_main

      - cypress/run:
          <<: *exclude_main
          name: integration_tests
          requires:
            - install_dependencies
          executor: default
          pre-steps:
            - checkout
            - *attach_workspace
            - *restore_cache
            - *yarn_install
          store_artifacts: true
          attach-workspace: true
          record: true # record results on Cypress Dashboard
          parallel: true # split all specs across machines
          parallelism: 4 # use X number of CircleCI machines
          command-prefix: yarn # dont use npx
          group: 'all tests' # name this group "all tests" on the dashboard
          start: 'yarn build && yarn start' # start server before running tests
          wait-on: http://localhost:3000 # wait until server is ready
```

I'm sure big improvements can happen once webpack 5 is used because of partial builds from cache, but I'm curious how saving a cache may even improve anything...

I would need to build first, send the build over as part of the workspace to the orb steps, and THEN start... right?
