### ISSUE TITLE
Multiple steps for build and post-install options

### ISSUE THREAD

**Issue by nicholaschiang** [cypress-io/circleci-orb#313]
## The orb does not work as expected

- what version of the orb are you currently using?
  * maybe the problem has been fixed already, check the orb releases at [cypress-io/circleci-orb/releases](https://github.com/cypress-io/circleci-orb/releases)

1.26.0

- paste the `circle.yml` file if possible or at least the relevant portion

```yaml
- cypress/install
  name: 'Setup Linux'
  yarn: true
  build:
    - run: echo 'This is a test command'
    - run: echo 'This is another test command'
```

- describe what you think should happen

Based on [the CircleCI documentation](https://circleci.com/docs/2.0/reusing-config/#steps), the `steps` parameter type should accept a list of commands like the one included above.

In [`src/orb.yml`](https://github.com/cypress-io/circleci-orb/blob/master/src/orb.yml#L293) the `build` parameter is assigned the `steps` type:

```yaml
      build:
        type: steps
        default: []
        description: Custom build commands to run after install
```

- describe what happens
  * screenshots and links to the CircleCI builds would be great

The [CircleCI build errors](https://app.circleci.com/pipelines/github/tutorbookapp/tutorbook/12/workflows/176e29bf-5100-4e29-b0f9-dd174636167d/jobs/17) saying that the parameter type was not as expected:
```
Error calling workflow: 'linux'
Error calling job: 'cypress/install'
Type error for argument build: expected type: string, actual value: "clojure.lang.LazySeq@fae3adad" (type sequence)
```
