### ISSUE TITLE
`node_modules` not cached when using yarn

### ISSUE THREAD

**Issue by dedan** [cypress-io/circleci-orb#321]
## The `node_modules` folder is not cached.

Orb version: cypress-io/cypress@1.26.0

```yaml
workflows:
  version: 2
  test-e2e:
    jobs:
      - cypress/install:
          yarn: true
          build: yarn build
```

During the installation step, I can see that the cache is restored. However, only `.cache` is restored but I would have expected also the `node_modules` folder to be restored from the cache. Here is the output from the restore cache step:

```
Found a cache at cache-arch1-linux-amd64-6_85-sg/fix-tests-MATvCrx+a2azQ1guTObB7Enh_ydPPWdw4rRH7sypr6I=
Size: 175 MiB
Cached paths:
  * /root/.cache
```

In the following step `yarn install --frozen-lockfile` is executed and this takes about 60s. If `node_modules` would have been in the cache, this should only take a few seconds.

When looking at the [description of the Orb](https://circleci.com/developer/orbs/orb/cypress-io/cypress), it sounds to me as if `node_modules` should be cached. However, in the actual definition of the Orb I don't see a caching path for `node_modules`. 

Are `node_modules` supposed to be cached automatically and if not, how can I do that?
