### ISSUE TITLE
locahost server issue 

### ISSUE THREAD

**Issue by mapipina** [cypress-io/circleci-orb#327]
## Orb and Docker Image result in localhost server error
I'm sure there is a simple solution to this but have not found a clearcut way to resolve. It seems every time CircleCi runs `npm start` it spins up a new server but our Cypress is set up to look for `http://localhost:3040` and not a dynamic host

- what version of the orb are you currently using? cypress-io/cypress@1

**cypress.json** 
```
{
    "baseUrl": "http://localhost:3040"
}
```

**CircleCi job using orb**
 ```
cypress/run:
          requires:
            - build
          command: npx cypress run 
          record: true
          store_artifacts: true
          start: npm start
          wait-on: 'http://localhost:3040'
```

**CircleCi job using Docker Image**
```
  cypress-test:
    docker: 
      - image: cypress/included:6.1.0
        environment:
          TERM: xterm
    working_directory: ~/repo
    steps:
      - checkout
      - restore_cache:
          keys:
            - v1-deps-{{ .Branch }}-{{ checksum "package.json" }}
            - v1-deps-{{ .Branch }}
            - v1-deps
      - run:
          name: Install Dependencies
          command: npm ci
      - save_cache:
          key: v1-deps-{{ .Branch }}-{{ checksum "package.json" }}
          paths:
            - ~/.npm
            - ~/.cache
      - run: 
          name: Start Server
          command: npm start
      - run: $(npm bin)/cypress run 
```
**Screenshots of error messages / failed tests**
![Screen Shot 2021-01-22 at 4 40 15 PM](https://user-images.githubusercontent.com/33269457/105765775-e593d980-5f26-11eb-94b2-27adf5929739.png)
![Screen Shot 2021-01-25 at 1 48 03 PM](https://user-images.githubusercontent.com/33269457/105765820-f6444f80-5f26-11eb-8bad-ab8ee8a5c980.png)
