### ISSUE TITLE
Can't run because no spec files were found.

### ISSUE THREAD

**Issue by nk-kaia** [cypress-io/circleci-orb#328]
## The orb does not work as expected
When I want to run all specs inside a folder in the integration folder (integration/regression) circle ci throws an error message describing that it cannot find any files matching the path. However, when I'm running the same command on my local machine, it works perfectly fine. 

This is the command that generates the error message in the CI: npx cypress run --spec 'cypress/integration/regression/*' 

- **Orb version:** 1.27.0
- Circle.yml file (relevant part):
```
  workflows:
  build:
    jobs:
      - cypress/run:
          record: true
          config: 'baseUrl=https://signup-bp.kaiahealth.com'
          spec: cypress/integration/regression/*
          # spec: cypress/integration/regression/10-corporate-verification-page.js - this one is not working too
          # spec: cypress/integration/smoke-test.js - this one is working 
```
- **What should happen**:
- All specs inside the regression folder should run.
- **What happens:**
 
<img width="585" alt="Screenshot 2021-02-10 at 10 46 02" src="https://user-images.githubusercontent.com/52247086/107497802-ae1a6380-6b9b-11eb-9f0b-680c2504262b.png">

**Folder structure**
<img width="257" alt="Screenshot 2021-02-10 at 11 00 02" src="https://user-images.githubusercontent.com/52247086/107498895-fd14c880-6b9c-11eb-9edf-c88852e5086f.png">
