### ISSUE TITLE
Only certified orbs are permitted in this project

### ISSUE THREAD

**Issue by thathurtabit** [cypress-io/circleci-orb#34]
Hi there.

Sorry if I'm missing something obvious here. I have enabled support for new CircleCI config 2.1 features within my CircleCI project, but when running CircleCI I get:

```
#!/bin/sh -eo pipefail
# Warning: Don't rerun. Rerunning will *not* recompile the config.
# Error loading cypress-io/cypress@1.0.0: only certified orbs are permitted in this project.
false
Exited with code 1
```

Any ideas?

**Comment by bahmutov** [comment]
Interesting, there might be some other setting? We have been using this orb without problems and it has been marked as "partner".  I see this question answered in https://github.com/circleci/circleci-docs/blob/master/jekyll/_cci2/orbs-faq.md#rerun-error but the answer does not really explain anything

**Comment by thathurtabit** [comment]
Unfortunately the suggestions there (i.e. trigger a rebuild via a config change) didn't help, though looking at the docs I may be missing something obvious.

Does the `npm i` command below refer to my local copy? Or install via SSH in CircleCI?

```

Examples
Install dependencies (using npm ci) and run all Cypress tests:

# to use orbs, must use version >= 2.1
version: 2.1
orbs:
  # import Cypress orb by specifying a version
  cypress: cypress-io/cypress@1.0.0
workflows:
  build:
    jobs:
      # "cypress" is the name of the imported orb
      # "run" is the name of the job defined in Cypress orb
      - cypress/run
```

**Comment by bahmutov** [comment]
@thathurtabit did you enable beta features in the circle project's configuration? under the advanced settings section

<img width="746" alt="screen shot 2018-11-15 at 2 05 08 pm" src="https://user-images.githubusercontent.com/2212006/48575267-80bcad80-e8df-11e8-8970-d84735560f4e.png">

**Comment by jennifer-shehane** [comment]
@bahmutov ^ I feel this should be clearer in the documentation, especially since I had trouble finding how to do this in their documentation.

**Comment by thathurtabit** [comment]
I did exactly that @bahmutov yeah (my set up already had this setting set this way)

**Comment by rkunev** [comment]
Took some digging to find the solution to this one. [Looks](https://circleci.com/docs/2.0/creating-orbs/#overview) like in order to even **use** 3rd party orbs that are not yet reviewed and approved by the CircleCI team you have to enable it through (and also like mentioned earlier enable build processing).
```
Settings -> Security -> Allow uncertified orbs
``` 
Source, if you want to skip opening the above link to the docs:

> 3rd-party orbs are those published by CircleCI customers and other members of our community. For you to publish orbs or for your projects to use 3rd-party orbs, your organization must opt-in under Security within the Settings tab under the Orb Security Settings where an organization administrator must agree to the terms for using 3rd-party software.

**Comment by thathurtabit** [comment]
Thanks @rkunev that seems to get around that first problem, however I'm now getting:

`#!/bin/sh -eo pipefail
# Error calling workflow: 'build'
# Error calling job: 'cypress/run'
# Cannot find orb 'cypress' looking for executor named 'cypress/base-10'
false
Exited with code 1`

My `.circleci/config.yml` looks like:

`# to use orbs, must use version >= 2.1
version: 2.1
orbs:
  # import Cypress orb by specifying a version
  cypress: cypress-io/cypress@1.0.0
workflows:
  build:
    jobs:
      # "cypress" is the name of the imported orb
      # "run" is the name of the job defined in Cypress orb
      - cypress/run`

The documentation mentions

`Install dependencies (using npm ci) and run all Cypress tests:`

Where does this install happen?

Thanks all.

**Comment by rkunev** [comment]
Got the same error as well and I'm not sure what's happening with `cypress/base-10` image. At first glance it seems that it should be available, but it just errors out. As a workaround I used Node.js 8
```yml
version: 2.1
orbs:
  cypress: cypress-io/cypress@1.0.0
workflows:
  build:
    jobs:
      - cypress/run:
          executor: cypress/base-8
```

**Comment by thathurtabit** [comment]
Thanks @rkunev - that workaround seems to work.

I've just run into this error now (but this is likely just down to setting the baseURL and CircleCI not being able to view it?):

```
#!/bin/bash -eo pipefail
npx cypress run \
   \
   \
  
Cypress could not verify that the server set as your 'baseUrl' is running:

  > http://localhost:3000

Your tests likely make requests to this 'baseUrl' and these tests will fail if you don't boot your server.

Please start this server and then run Cypress again.
Exited with code 1
```

**Comment by bahmutov** [comment]
Do you have a running server at localhost 3000?

**Comment by thathurtabit** [comment]
@bahmutov, my bad, I had missed the `start` param - the following works:

```
version: 2.1
orbs:
  cypress: cypress-io/cypress@1.0.0
workflows:
  build:
    jobs:
      - cypress/run:
          executor: cypress/base-8
          start: 'npm start' # start server before running tests
```
