### ISSUE TITLE
update nodejs on executors or publish more versions

### ISSUE THREAD

**Issue by cromega** [cypress-io/circleci-orb#350]
## The orb does not work as expected

- what version of the orb are you currently using?

1.28.0

The `cypress/base-14` executor has nodejs 0.14.7, which happens to be too old for one of our transient dependencies. It would be nice if there were more executor versions to choose from, including latest versions.

**Comment by bbaia** [comment]
None of the actual node version supports Angular 13 :

> Node.js version v14.7.0 detected.
The Angular CLI requires a minimum Node.js version of either v12.20, v14.15, or v16.10.

**Comment by bbaia** [comment]
There is a workaround using a docker image available here :
https://hub.docker.com/r/cypress/base/tags

```
version: 2.1
orbs:
  cypress: cypress-io/cypress@1
executors:
  base-14-17-3:
    docker:
      - image: 'cypress/base:14.17.3'
workflows:
  build:
    jobs:
      - cypress/run:
          executor: base-14-17-3
```
