### ISSUE TITLE
Failed to launch the browser process!

### ISSUE THREAD

**Issue by Spiroman** [cypress-io/circleci-orb#362]
## The orb does not work as expected

- what version of the orb are you currently using?
  * 1.29.0
- paste the `circle.yml` file if possible or at least the relevant portion
```
- cypress/run:
    group: "minta-ecom-auth-test"
    record: true
    spec: cypress/integration/auth-shopify.spec.js
```
- describe what you think should happen
I expected cypress to run the e2e tests without an issue...
- describe what happens
The process fails to run with the following error: `> Error: Failed to launch the browser process!
[728:728:0830/042320.872842:ERROR:zygote_host_impl_linux.cc(90)] Running as root without --no-sandbox is not supported. See https://crbug.com/638180.`
I also want to note that this issue started when we added puppeteer as part of our cypress run. 
![Screen Shot 2021-08-31 at 11 50 40](https://user-images.githubusercontent.com/6946401/131472794-36a4a7d2-3608-4b72-8085-8350cd20b600.png)

Would it be possible to pass this additional flag (`--no-sandbox`) to the execution
