### ISSUE TITLE
Bug: Unable to pass environment variables to the cypress process

### ISSUE THREAD

**Issue by ofekudi** [cypress-io/circleci-orb#366]
## The orb does not work as expected

- what version of the orb are you currently using? 
    - 1.29.0
- paste the `circle.yml` file if possible or at least the relevant portion
    - I attach the relevant parts of the file at the bottom
- describe what you think should happen
    - When I try to access the environment variable using `Cypress.env('FOO')` or `process.env.FOO` I receive `undefined`
- describe what happens
    - No environment variables are passed into the cypress

config.yml:

```
version: 2.1
orbs:
  cypress: cypress-io/cypress@1.29.0
executors:
  with-node16:
    docker:
      - image: 'cypress/base:16.13.0'
    environment:
      FOO: foo
      BAR: bar

workflows:
  version: 2
  build:
    jobs:
      - cypress/run:
          executor: 'with-node16'
```
