### ISSUE TITLE
Can we get a node-16 executor?

### ISSUE THREAD

**Issue by adam-lynch** [cypress-io/circleci-orb#368]
There should be an executor to run on node 16. The max is 14 according to https://circleci.com/developer/orbs/orb/cypress-io/cypress#executors.

I haven't ran into an issue yet but we've had some local issues with our `postinstall` scripts on node 14 so we're bumping to 16 and I want to run the Cypress job on 16 too.

See https://nodejs.org/en/about/releases/; node 16, 17, and 18 should probably be supported.

**Comment by essential-randomness** [comment]
Came here to ask the same thing :)

**Comment by FinnLawrence** [comment]
For anyone who needs Node 16 support in the meantime, I have set our builds up to use a customised docker executor from Cypress's list here: https://github.com/cypress-io/cypress-docker-images/tree/master/browsers

Example config:
```
version: 2.1
orbs:
  cypress: cypress-io/cypress@1.29.0
executors:
  with-chrome:
    resource_class: small
    docker:
      - image: "cypress/browsers:node16.13.0-chrome95-ff94"
workflows:
  build:
    jobs:
      - cypress/install:
          executor: with-chrome
          ....
      - [your other jobs]
          executor: with-chrome
          ....
```
