### ISSUE TITLE
Restore Cache `permission denied` failure, CYPRESS_CACHE_FOLDER seemingly ignored.

### ISSUE THREAD

**Issue by benterova** [cypress-io/circleci-orb#402]
## The orb does not work as expected

- what version of the orb are you currently using?
2.2.0
  
- paste the `circle.yml` file if possible or at least the relevant portion
```
executors:
  ruby-node:
    docker:
      - image: cimg/ruby:2.7-browsers
      - image: cimg/node:16.14.2-browsers
    environment:
      CYPRESS_CACHE_FOLDER: ~/.cache/Cypress
      BUNDLE_JOBS: "3"
      BUNDLE_RETRY: "3"
      PGHOST: 127.00.1
      PGUSER: circleci
      PGDATABASE: [redacted]
      PGPASSWORD: "[redacted]"
      RAILS_ENV: test
      RACK_ENV: test

workflows:
  build_and_test:
    jobs:
      - cypress/run:
          post-checkout:
            - ruby/install-deps:
                pre-install-steps:
                  - run:
                      name: Set CYPRESS_CACHE_FOLDER
                      command: echo "export CYPRESS_CACHE_FOLDER=~/.cache/Cypress" >> $BASH_ENV
                  - run:
                      name: Install python and pip.
                      command: sudo apt-get update && sudo apt-get -y install python2
          start: RAILS_ENV=test bundle exec rails s -p 3000
          yarn: true
          executor: ruby-node
          verify-command: yarn cypress verify
          wait-on: http://localhost:3000
```
- describe what you think should happen
  * CYPRESS_CACHE_FOLDER should be honored and not default to `/root/.cache/Cypress/7.7.0/Cypress/` when parameter is specified.
- describe what happens
  * CYPRESS_CACHE_FOLDER is not honored, and when attempting to restore cache error `mkdir /root/.cache: permission denied` is presented.

I've attempted to set this CYPRESS_CACHE_FOLDER using two different methods and neither of them seem to have any effect.
