### ISSUE TITLE
Is there any ways to use self-hosted runner in Cypress orb?

### ISSUE THREAD

**Issue by andikabhaskara** [cypress-io/circleci-orb#407]
- what version of the orb are you currently using?
  * cypress-io/cypress@2

- paste the `circle.yml` file if possible or at least the relevant portion
````
version: 2.1
orbs:
  cypress: cypress-io/cypress@2
executors:
  personal:
    machine: true
    resource_class: <my-namespace>/<my-runner>
workflows:
  build:
    jobs:
      - cypress/install
      - cypress/run:
          executors: personal
          requires:
            - cypress/install
          record: true
          parallel: true
          parallelism: 2
          group: Test e2e
````

- describe what you think should happen
Hi guys, I am new in the implementation of cypress and I hope I at the right section of discussion to ask this question. I would like to ask, Is there any ways that I could use self hosted runner in Cypress orb? I tried to use the executors command, However, it seems doesn't work out (either I implement it wrong, or it haven't support yet) 

any help would be appreciated. Thanks guys!
