### ISSUE TITLE
cypress/run-tests installing YARN packages?

### ISSUE THREAD

**Issue by mattkoch-bb** [cypress-io/circleci-orb#417]
##  cypress/run-tests installing YARN packages?

I have the following job in my CircleCI config, and was expecting that it not install YARN packages. 

https://circleci.com/developer/orbs/orb/cypress-io/cypress#commands-run-tests 

```yaml
  acceptance:
    docker:
      - image: cypress/included:cypress-12.6.0-node-16.18.1-chrome-110.0.5481.96-1-ff-109.0-edge-110.0.1587.41-1
    parallelism: 1
    steps:
      - checkout
      - attach_workspace:
          at: ~/
      - cypress/run-tests:
          working-directory: nextjs
          start-command: npx wrangler pages dev out
          cypress-command: npx cypress run --config video=false,baseUrl=http://localhost:8788
```

With this setup, I observed that CircleCI still runs a `yarn install` step - am I missing a parameter or configuration step?
