### ISSUE TITLE
v3 orb missing artifacts from Cloud (video/ screenshots)

### ISSUE THREAD

**Issue by conversayShawn** [cypress-io/circleci-orb#418]
## The orb does not work as expected

- what version of the orb are you currently using?

  v3

- paste the `circle.yml` file if possible or at least the relevant portion
 
```
version: 2.1
orbs:
  cypress: cypress-io/cypress@3
workflows:
  use-my-orb:
    jobs:
      - cypress/run:
          cypress-command: npx cypress run --parallel --record
          parallelism: 3
```
          
- describe what you think should happen

artifacts uploaded to the Cypress Cloud should also be available in the CircleCI Dashboard for v3

- describe what happens

Artifacts are uploaded to the Cypress Cloud. 
Artifacts are not available in CircleCI Dashboard
The `store_artifacts: true` option is throws 

```
Error calling workflow: 'use-my-orb'
Error calling job: 'cypress/run'
Unexpected argument(s): store_artifacts
```

![Screen Shot 2023-03-15 at 3 38 23 PM](https://user-images.githubusercontent.com/48733734/225648425-ca25effe-e7d8-4da8-91db-d4e4cae2ec56.png)

![Screen Shot 2023-03-16 at 7 40 40 AM](https://user-images.githubusercontent.com/48733734/225652778-3c6a7bab-a3b6-4587-9b10-ba29c6380890.png)

**Comment by lmiller1990** [comment]
<img width="541" alt="image" src="https://user-images.githubusercontent.com/19196536/225825936-38d983c2-e5b7-453c-8c09-bf79035c3312.png">
 
Looks like it is trying to find the artifacts in the absolute directory `/cypress/videos`... this should be relative, right?

The examples in this repo are working, though: https://app.circleci.com/pipelines/github/cypress-io/circleci-orb/1848/workflows/b08b90eb-6c21-4ba5-8055-8bd3c5b50cdc/jobs/5430 🤔

**Comment by lmiller1990** [comment]
Hi @conversayShawn, I synced with @jordanpowell88 but the issue *appears* to be on the cloud end, not the orb itself. I'm still not entirely clear on this, I'll keep looking into it.

**Comment by lmiller1990** [comment]
For internal team, here's a [discussion about this on Slack](https://cypressio.slack.com/archives/C03MAAAQGN5/p1677684716387199) from a while ago.

**Comment by emilyrohrbough** [comment]
@conversayShawn If you specify the working-directory as `.` does this solve your issue?

```diff
    jobs:
      - cypress/run:
          cypress-command: npx cypress run --parallel --record
+         working-directory: '.'
          parallelism: 3
```

**Comment by conversayShawn** [comment]
@emilyrohrbough Unfortunately, it did not 😭

Would debug logs be helpful? And if so, which filters should I use? `DEBUG=cypress:*`

**Comment by emilyrohrbough** [comment]
@conversayShawn Darn, was wondering if that would remove the absolute path issue @lmiller1990 pointed out because our default `working-directory` value is `""` in the v3 orb. Can you post a link to the Job that ran with this update? No need for Cypress debug-logs as its a CircleCI setup issue not a Cypress-app issue.

**Comment by conversayShawn** [comment]
Actually, I have some good news! There must have been a delay in uploading: https://app.circleci.com/pipelines/github/conversayShawn/circle_ci/53/workflows/4a099252-1198-4c8a-8d27-a3f51c88dc51/jobs/62/artifacts

Looks like that resolved the issue!

**Comment by emilyrohrbough** [comment]
@conversayShawn Ah yay! That essentially means our default value is wrong and should be updated from `""` to `"."` [here](https://github.com/cypress-io/circleci-orb/blob/master/src/commands/run-tests.yml#L8).

**Comment by disrael** [comment]
@emilyrohrbough I still had to use the workaround in order to make this work:
      - cypress/run:
          requires:
            - prepare_ruby
            - prepare_python
          install-command: 'npm install --no-optional --unsafe-perm'
          working-directory: '.'

This is with:
cypress: cypress-io/cypress@3

**Comment by tmannherz** [comment]
@emilyrohrbough as @disrael said above, if you're running the `cypress/run` job in your workflow, you'll still have to pass the `working-directory` param for screenshots/videos to be stored, as of Orb version 3.3.1. 

While the merged fix above set a default working directory for the `run-tests` command, the `cypress/run` job still has a default working directory of `""`: https://github.com/cypress-io/circleci-orb/blob/v3.3.1/src/jobs/run.yml#L49

Won't store screenshot artifacts: ❌ 
```yaml
version: 2.1
orbs:
  cypress: cypress-io/cypress@3.3.1
workflows:
  build:
    jobs:
      - cypress/run:
          cypress-command: npx cypress run
```

Will store screenshot artifacts: ✅ 
```yaml
version: 2.1
orbs:
  cypress: cypress-io/cypress@3.3.1
workflows:
  build:
    jobs:
      - cypress/run:
          cypress-command: npx cypress run
          working-directory: .
```
