### ISSUE TITLE
Edge support documentation

### ISSUE THREAD

**Issue by paulfalgout** [cypress-io/circleci-orb#419]
The documentation for edge is either incorrect or confusing.  The example shows
```yaml
version: '2.1'
orbs:
  cypress: cypress-io/cypress@3
workflows:
  use-my-orb:
    jobs:
      - cypress/run:
          cypress-command: npx cypress run --browser edge
          install-browsers: true
          start-command: 'npm run start:dev'
```

But the `install-browsers` command description says:
```
Cypress runs by default in the Electron browser. Use this flag to install additional browsers to run your tests in. This is only needed if you are passing the `--browser` flag in your `cypress-command`. This parameter leverages the `circleci/browser-tools` orb and includes Chrome and FireFox. If you need additional browser support you can set this to false and use an executor with a docker image that includes the browsers of your choosing.
```

This seems to indicate that `install-browsers` should be `false` for edge and we should load an `executor`?  Is the Edge example incorrect or am I missing something?
