### ISSUE TITLE
Is it possible to use node 18 ? 

### ISSUE THREAD

**Issue by sk-roofr** [cypress-io/circleci-orb#424]
## The orb does not work as expected

- what version of the orb are you currently using?
  cypress-io/cypress@3.1.1
  
- paste the `circle.yml` file if possible or at least the relevant portion
```
  cypress-component-test:
    jobs:
      - cypress/run:
          package-manager: yarn
          cypress-command: npx cypress run --component
```
- describe what you think should happen
Expecting to pass node version or cypress docker image name
- describe what happens

I am unable to run it because our default node engine is 18
`Expected version "^18". Got "16.16.0"`
