### ISSUE TITLE
cypress/run has no executor param

### ISSUE THREAD

**Issue by Phonesis** [cypress-io/circleci-orb#429]
It appears that with v3 of the orb you can no longer specify a specific executor for browsers when using the cypress/run command/job. 

It appears to only be available for cypress/run-tests. 

Is this intended? If so, the documentation is not clear or useful. For the install-browser param it says: 

```
f you need additional browser support you can set this to false and use an executor with a docker image that includes the browsers of your choosing. See https://hub.docker.com/r/cypress/browsers/tags
```

How do you do this for cypress/run? 

I would expect this to be valid: 

```
      - cypress/run:
          name: cypress-uat-tests
          install-browsers: false
          executor: <my docker image> 
```
