### ISSUE TITLE
Store test result?

### ISSUE THREAD

**Issue by olaj** [cypress-io/circleci-orb#43]
In the docs for the docker version of running tests with cypress you had an example of [storing the test result in Circle CI](https://github.com/cypress-io/cypress-example-docker-circle#test-summary), i can't find any similar documentation for the orb version? Am i missing something?

**Comment by bahmutov** [comment]
No, we have not implemented a similar command here to invoke [store_test_results](https://circleci.com/docs/2.0/configuration-reference/#store_test_results) but it would be simple to do so I believe. For now you can use `record: true` to send test results to the Cypress Dashboard though

**Comment by cowley05** [comment]
We tried to use `record: true` within our circle ci yaml file, we're on a free tier and get the following error when we run our build:
```
#!/bin/bash -eo pipefail
npx cypress run \
   \
   \
   --record \
    --group 'default group' \
     \
Grouping is not included under your current billing plan.

To run your tests with groups, please visit your billing and upgrade to another plan with grouping.
...
```

We don't have a group set, is it possible to do this on the free tier?

Links to our project ci server and github repository are below:

https://circleci.com/gh/build-canaries/nevergreen/1224

https://github.com/build-canaries/nevergreen/blob/51e67aca6bb52d2f89cf3e2da820fa6d074476b4/.circleci/config.yml#L184

**Comment by bahmutov** [comment]
@olaj I would be open to PR to save results (but what folder?) similar to the way I have added `test_artifacts` support here https://github.com/cypress-io/circleci-orb/commit/1be3a7c3c0060a54a49427e81db2274cd311810f#diff-6c9e2aec07085a034628a6e91620f07bR204

**Comment by bahmutov** [comment]
I think this should be possible by adding `post` job commands, need to verify and write an example

**Comment by leogoesger** [comment]
status on this? 
`#!/bin/bash -eo pipefail
npx cypress run \
   \
   \
   --record \
    --group 'default group' \
     \
Grouping is not included under your current billing plan.`

**Comment by bahmutov** [comment]
@leogoesger I think you need a later version of the orb - this has been fixed in version 1.1.2 https://github.com/cypress-io/circleci-orb/releases/tag/v1.1.2

**Comment by bahmutov** [comment]
Store generated test reports like this:

```yaml
version: 2.1
orbs:
  cypress: cypress-io/cypress@1
workflows:
  build:
    jobs:
      # checks out code and installs dependencies once
      - cypress/run:
          command: 'npm run cy:run -- --record false'
          post-steps:
            - store_test_results:
                path: cypress/results
```
