### ISSUE TITLE
Add a way to set the Chrome versions when using install-browsers

### ISSUE THREAD

**Issue by lems3** [cypress-io/circleci-orb#439]
With the latest issues and changes with The Chrome and Chrome Driver release cycle, it may be useful to have an easy way to override the Chrome version.

I feel that it would only need an additional parameter to pass this to the browser-tools/install-browser-tools step.

**Comment by MikeMcC399** [comment]
@lems3

This is quite an old request, and it looks like you are no longer active in GitHub, however we've just updated the Cypress Orb's `install-browsers` flag to include Microsoft Edge and Google Chrome for Testing, so it makes sense to comment now.

`install-browsers: true` installs all applicable browsers and drivers from the [circleci/browser-tools](https://circleci.com/developer/orbs/orb/circleci/browser-tools) orb, which are by now:

- Chrome
- Chrome for Testing
- Edge
- Firefox + geckodriver

There is no flexibility in the CircleCI Cypress orb to choose which browser or which browser version to install. To bring this into the CircleCI Cypress orb would duplicate the function of the [circleci/browser-tools](https://circleci.com/developer/orbs/orb/circleci/browser-tools) orb, making the Cypress orb more complex and more difficult to maintain.

To achieve the desired result, it is possible to access both the Cypress orb and the browser-tools orb in the same CircleCI pipeline configuration, allowing maximum flexibility in browser choice, for example, the following `.circleci/config.yml` tests with Cypress against a defined browser version:

```yml
version: '2.1'
orbs:
  cypress: cypress-io/cypress@4 # https://circleci.com/developer/orbs/orb/cypress-io/cypress
  browser-tools: circleci/browser-tools@2 # https://circleci.com/developer/orbs/orb/circleci/browser-tools
jobs:
  electron-test:
    executor: cypress/default
    steps:
      - cypress/install
      - cypress/run-tests
  chrome-test:
    executor: cypress/default
    steps:
      - cypress/install
      - browser-tools/install_chrome:
          chrome_version: 137.0.7151.68
      - cypress/run-tests:
          cypress-command: npx cypress run --browser chrome
  chrome-for-testing-test:
    executor: cypress/default
    steps:
      - cypress/install
      - browser-tools/install_chrome_for_testing:
          version: 137.0.7151.68
      - cypress/run-tests:
          cypress-command: npx cypress run --browser chrome-for-testing
  edge-test:
    executor: cypress/default
    steps:
      - cypress/install
      - browser-tools/install_edge:
          version: 137.0.3296.62
      - cypress/run-tests:
          cypress-command: npx cypress run --browser edge
  firefox-test:
    executor: cypress/default
    steps:
      - cypress/install
      - browser-tools/install_firefox:
          version: 139.0.1
      - cypress/run-tests:
          cypress-command: npx cypress run --browser firefox
workflows:
  all-browsers:
    jobs:
      - electron-test
      - chrome-test
      - chrome-for-testing-test
      - edge-test
      - firefox-test
```

I propose to close this feature request, since there is a workable alternative that does not need any additional development.
