### ISSUE TITLE
How to install nested dependencies?

### ISSUE THREAD

**Issue by danawoodman** [cypress-io/circleci-orb#44]
I have a project where I have a `server` folder which has its own `package.json` file. The orb does not seem to install any of these dependencies, despite my root `package.json` having a `postinstall` step in it which works fine in development.

```
my-app/
    |_ package.json
    |_ package-lock.json
    server/  <-- dependencies don't get installed
      |_ package.json
      |_ package-lock.json

```

I assume this is because `npm ci` doesn't use `package.json`? If so, how can I install a nested folder's dependencies?

I have tried many things, including just running `npm run postinstall` or `cd server && npm i` in the `build` step of `cypress/install` but nothing seems to work.

Here is my current `circle.yml` file:

```yml
version: 2.1
orbs:
  cypress: cypress-io/cypress@1.1.0
workflows:
  build:
    jobs:
      - cypress/install:
          build: 'npm run build && npm run postinstall'
      - cypress/run:
          requires:
            - cypress/install
          group: portal
          start: npm run server
          wait-on: 'http://localhost:3000'
```

I'd very much appreciate some guidance, I'm excited to get Cypress working with my CI so I can start writing more tests!

Thanks!

**Comment by bahmutov** [comment]
so the orb uses `npm ci` command to install dependencies - and you are saying it does not execute `postinstall` step? That is weird, because Cypress binary itself is installed during `postinstall` step. 

- can you post the output from the install command?
- can you rerun workflow without previous Circle cache?
- can you look at the effective Circle config? Maybe there is something that would jump at you there

**Comment by danawoodman** [comment]
Output from "npm ci" task:

```
#!/bin/bash -eo pipefail
npm ci

> parse-domain@2.1.1 postinstall /root/project/node_modules/parse-domain
> node scripts/build-tries.js

Downloading public suffix list from https://publicsuffix.org/list/public_suffix_list.dat... ok
Writing /root/project/node_modules/parse-domain/build/tries/current/icann.complete.json... ok
Writing /root/project/node_modules/parse-domain/build/tries/current/icann.light.json... ok
Writing /root/project/node_modules/parse-domain/build/tries/current/private.complete.json... ok
Running sanity check... ok

> cypress@3.1.2 postinstall /root/project/node_modules/cypress
> node index.js --exec install


Cypress 3.1.2 is already installed in /root/.cache/Cypress/3.1.2


> fsevents@1.2.4 install /root/project/node_modules/fsevents
> node install

npm WARN lifecycle my-app@1.0.0~postinstall: cannot run in wd my-app@1.0.0 cd server && npm install (wd=/root/project)
added 2291 packages in 5.436s
```

The last line seems like it is a clue?

How can I re-run the build without cache? Seems like Circle has no option for this? (which is just crazy!)

Here is the "effective" config:

```
# Orb 'cypress-io/cypress@1.1.0' resolved to 'cypress-io/cypress@1.1.0'
version: 2
jobs:
  cypress/install:
    docker:
    - image: cypress/base:10
    steps:
    - checkout
    - restore_cache:
        keys:
        - cache-{{ .Branch }}-{{ checksum "package.json" }}
    - run:
        name: Npm CI
        command: npm ci
    - run:
        command: npx cypress verify
    - save_cache:
        key: cache-{{ .Branch }}-{{ checksum "package.json" }}
        paths:
        - ~/.npm
        - ~/.cache
    - run:
        command: npm run build && npm run postinstall
    - persist_to_workspace:
        root: ~/
        paths:
        - project
        - .cache/Cypress
  cypress/run:
    docker:
    - image: cypress/base:10
    parallelism: 1
    steps:
    - checkout
    - restore_cache:
        keys:
        - cache-{{ .Branch }}-{{ checksum "package.json" }}
    - run:
        name: Npm CI
        command: npm ci
    - run:
        command: npx cypress verify
    - save_cache:
        key: cache-{{ .Branch }}-{{ checksum "package.json" }}
        paths:
        - ~/.npm
        - ~/.cache
    - persist_to_workspace:
        root: ~/
        paths:
        - project
        - .cache/Cypress
    - run:
        name: Start
        command: npm run server
        background: true
    - run:
        name: Wait-on http://localhost:3000
        command: npx wait-on http://localhost:3000
    - run:
        name: Run Cypress tests
        command: "npx cypress run \\\n   \\\n   \\\n  "
workflows:
  build:
    jobs:
    - cypress/install
    - cypress/run:
        requires:
        - cypress/install
  version: 2

```
