### ISSUE TITLE
Install Chromedriver returns 404

### ISSUE THREAD

**Issue by LeandroTorresSicilia** [cypress-io/circleci-orb#446]
## The orb does not work as expected

- what version of the orb are you currently using?
3.2.0
- paste the `circle.yml` file if possible or at least the relevant portion
```
version: 2.1

orbs:
  node: circleci/node@5.1.0
  cypress: cypress-io/cypress@3.2.0

jobs:
  lint_and_test:
    docker:
      - image: cimg/node:18.16.0-browsers
    steps:
      - checkout
      - node/install-packages:
          pkg-manager: yarn
      - run: yarn install
      - run: yarn lint
      - run: yarn test-ci

  deploy:
    docker:
      - image: cimg/node:18.16.0-browsers
    steps:
      - checkout
      - node/install-packages:
          pkg-manager: yarn
      - run: yarn install
      - run:
          name: Deploy Firebase Hosting
          command: yarn deploy

workflows:
  test_and_deploy:
    jobs:
      - lint_and_test
      - cypress/run:
          requires:
            - lint_and_test
          install-command: yarn install
          start-command: yarn start
          cypress-command: npx wait-on@latest http://localhost:3000 && npx cypress run --browser chrome
          install-browsers: true
      - deploy:
          requires:
            - cypress/run
          filters:
            branches:
              only: master

```
- describe what you think should happen
It should not fail when installing chromedriver
- describe what happens
![Screenshot 2023-12-06 at 9 56 18 AM](https://github.com/cypress-io/circleci-orb/assets/24737097/796161c8-c420-46a0-aab1-f22e59a27fe9)
