### ISSUE TITLE
Install ChromeDriver 404 error with install-browsers flag

### ISSUE THREAD

**Issue by johnkim-det** [cypress-io/circleci-orb#460]
## The orb does not work as expected

- what version of the orb are you currently using? 3.3.0
- paste the `circle.yml` file if possible or at least the relevant portion
```
version: 2.1

orbs:
  cypress: cypress-io/cypress@3.3.0

workflows:
  main:
    jobs:
      - cypress/run:
          install-browsers: true
          cypress-command: 'npx cypress run --component --browser chrome --headed'
```
- describe what you think should happen
Should install
- describe what happens
Error at Install ChromeDriver step:

```
Chrome version major is 122
Installed version of Google Chrome is 122.0.6261.94 
404
Matching Chrome Driver Version 404'd, falling back to first matching major version.
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100   937  100   937    0     0  13573      0 --:--:-- --:--:-- --:--:-- 13779
New ChromeDriver version to be installed: 122.0.6261.94
122.0.6261.94 will be installed
curl: (22) The requested URL returned error: 404

Exited with code exit status 22
```

Tried multiple versions (3.3.0, 3.2.1, 3.2.0, 3.1.4, 3.1.3), all with the same error.
