### ISSUE TITLE
CircleCI stuck on Installing NPM packages

### ISSUE THREAD

**Issue by TrystanCars** [cypress-io/circleci-orb#466]
## The orb does not work as expected

Version: `cypress-io/cypress@3.3.1`

```
run-tests:
    executor: cypress/default
    steps:
      - attach_workspace:
          at: .
      - cypress/install
      - cypress/run-tests:
          cypress-command: npx wait-on@latest http://localhost:3000 && npx cypress run --record false
          start-command: 'npm run start'
```

When running the above on CircleCI - CircleCI hangs on the Installing NPM packages step.
