### ISSUE TITLE
Docs for running with a specified node-version doesn't show how to change node version

### ISSUE THREAD

**Issue by laurie-wrisk** [cypress-io/circleci-orb#468]
The docs here: https://circleci.com/developer/orbs/orb/cypress-io/cypress#usage-node-version, says this is the way to change the node version for the orb:

```
version: '2.1'
orbs:
  cypress: cypress-io/cypress@3
workflows: null
```

But node version isn't specified anywhere here

**Comment by MikeMcC399** [comment]
@laurie-wrisk 

The contents of https://circleci.com/developer/orbs/orb/cypress-io/cypress#usage-node-version (which you posted above) differ from https://github.com/cypress-io/circleci-orb/blob/master/src/examples/node-version.yml which contains:

```yml
description: >
  Run Cypress tests using the cypress/default executor with a specified node version.
usage:
  version: 2.1
  orbs:
    cypress: cypress-io/cypress@3
jobs:
  run-cypress-in-specified-node-version:
    executor:
      name: cypress/default
      node-version: "20.6"
    steps:
      - cypress/install:
          package-manager: "yarn"
      - cypress/run-tests:
          start-command: "npm run start:dev"
          cypress-command: "npx cypress run"
workflows:
  use-my-orb:
    jobs:
      - run-cypress-in-specified-node-version:
          name: Run Cypress in Node 20
```

I guess the two different text portions should be aligned.

It seems strange to define `yarn` as `package-manager` and then run a script with `npm` instead of `yarn`, but that doesn't hurt the `node-version` selection.

**Comment by jennifer-shehane** [comment]
Yah I'm not sure what's happened with the generated docs on the orb website. There's some usages of node-version in the repo itself: https://github.com/search?q=repo%3Acypress-io%2Fcircleci-orb%20node-version&type=code

I have no idea why that node-version file has mixed package managers either. Probably just an oversight when we last rewrote the orb.

**Comment by MikeMcC399** [comment]
@jennifer-shehane 

Are the docs supposed to be published automatically or is that a manual job to update them? The `node-version` search doesn't really bring any additional enlightenment on top of reading the full https://github.com/cypress-io/circleci-orb/blob/master/src/examples/node-version.yml.

- I did at least manage to apply this to https://github.com/cypress-io/cypress-example-kitchensink/pull/859 to resolve the issue by converting from `cypress/run` to `cypress/run-tests`.

## command cypress/run-tests

To resolve this issue (#468), the example text from

- https://github.com/cypress-io/circleci-orb/blob/master/src/examples/node-version.yml

dealing with how to set [node-version](https://circleci.com/developer/orbs/orb/cypress-io/cypress#usage-node-version) together with the command [cypress/run-tests](https://circleci.com/developer/orbs/orb/cypress-io/cypress#commands-run-tests) needs to be corrected and then published to

- https://circleci.com/developer/orbs/orb/cypress-io/cypress#usage-node-version

## job cypress/run

If there is an example for use together with the job [cypress/run](https://circleci.com/developer/orbs/orb/cypress-io/cypress#jobs-run), then that should be added. If it is not possible to select a different Node.js version for use with the job [cypress/run](https://circleci.com/developer/orbs/orb/cypress-io/cypress#jobs-run), then that should be explicitly stated in the documentation.

**Comment by jennifer-shehane** [comment]
@MikeMcC399 I feel like the actual orb doc updates if you release a new version. I don't recall ever updating the docs independently so I'm not sure if that's possible. Seems like it should be possible though.

**Comment by MikeMcC399** [comment]
@jennifer-shehane 

> I feel like the actual orb doc updates if you release a new version. I don't recall ever updating the docs independently so I'm not sure if that's possible. Seems like it should be possible though.

I can't be of much assistance here as this part of interacting with CircleCI is only practical with Cypress.io access privileges. I have to leave it to your team to sort out. If things aren't working the way they should, then you may need to involve CircleCI support.

**Comment by MikeMcC399** [comment]
- The new example https://github.com/cypress-io/circleci-orb/blob/master/src/examples/node-version.yml from PR https://github.com/cypress-io/circleci-orb/pull/484 hasn't been published to https://circleci.com/developer/orbs/orb/cypress-io/cypress#usage-node-version. Nothing has changed and this issue is still unresolved.

```yml
description: >
  Run Cypress tests using the cypress/default executor with a specified node version.
usage:
  version: 2.1
  orbs:
    cypress: cypress-io/cypress@3
jobs:
  run-cypress-in-specified-node-version:
    executor:
      name: cypress/default
      node-version: "20.6"
    steps:
      - cypress/install:
          package-manager: "npm"
      - cypress/run-tests:
          start-command: "npm run start:dev"
          cypress-command: "npx cypress run"
workflows:
  use-my-orb:
    jobs:
      - run-cypress-in-specified-node-version:
          name: Run Cypress in Node 20

```

**Comment by jennifer-shehane** [comment]
Ah, pretty annoying. I feel like this might have happened before. 🤔

**Comment by MikeMcC399** [comment]
@jennifer-shehane 

> Ah, pretty annoying. I feel like this might have happened before. 🤔

Yes, it has happened before.

The [publish log](https://app.circleci.com/pipelines/github/cypress-io/circleci-orb/1970/workflows/e2ce1415-1eec-42e3-a44c-19edff99cd5a/jobs/6937/parallel-runs/0/steps/0-102) works silently giving no helpful details:

```text
Preparing to publish your orb.
Production release detected!
Production version: 3.4.0

Once an orb is created it cannot be deleted. Orbs are semver compliant, and each published version is immutable. Publicly released orbs are potential dependencies for other projects.
Therefore, allowing orb deletion would make users susceptible to unexpected loss of functionality.
Orb `cypress-io/cypress@3.4.0` was published.
Please note that this is an open orb and is world-readable.



********************************************************************************
Your orb has been published to the CircleCI Orb Registry.
You can view your published orb on the CircleCI Orb Registry at the following link: 
https://circleci.com/developer/orbs/orb/cypress-io/cypress?version=3.4.0

```

**Comment by deiga** [comment]
I think it might be an indentation problem, drafting a PR

**Comment by MikeMcC399** [comment]
@deiga 

> I think it might be an indentation problem, drafting a PR

- It's good to correct the indentation in PR #487. I'm unsure if this is the only issue however since the edge example is also not getting published (see https://github.com/cypress-io/circleci-orb/issues/482).

**Comment by deiga** [comment]
> @deiga 
> 
> 
> 
> > I think it might be an indentation problem, drafting a PR
> 
> 
> 
> - It's good to correct the indentation in PR #487. I'm unsure if this is the only issue however since the edge example is also not getting published (see https://github.com/cypress-io/circleci-orb/issues/482).

@MikeMcC399 
I'm not sure it's the same issue. Looking at it, it seems that the example is published correctly, but the published example is not a working one

**Comment by MikeMcC399** [comment]
@jennifer-shehane 

If you want to cut a new orb release the node documentation has a good chance of being correctly published now:

Preview on https://circleci.com/developer/orbs/orb/cypress-io/cypress?version=dev:b3455e432dad1a6db0f19889495ebcf62577fa3d#usage-node-version shows:

![image](https://github.com/user-attachments/assets/1c05566e-693f-4ce6-922a-0ea2d5ed7322)

**Comment by jennifer-shehane** [comment]
Tried to release this, but the job is failing: https://github.com/cypress-io/circleci-orb/pull/492#issuecomment-2458030173

**Comment by MikeMcC399** [comment]
- Issue https://github.com/cypress-io/circleci-orb/issues/493 opened and PR https://github.com/cypress-io/circleci-orb/pull/494 submitted

**Comment by MikeMcC399** [comment]
CircleCI workflow log for failed `v3.4.1` release https://app.circleci.com/pipelines/github/cypress-io/circleci-orb/1980 shows `dev:alpha` published on https://app.circleci.com/pipelines/github/cypress-io/circleci-orb/1980/workflows/8344eaa2-bceb-4654-b0b7-bd7e30a9a6df/jobs/7056 

> Your development orb has been published. It will expire in 30 days.
> You can preview what this will look like on the CircleCI Orb Registry at the following link: 
> https://circleci.com/developer/orbs/orb/cypress-io/cypress?version=dev:98eca619c68c9db6fcff36aa1c92701265a5e76c

shows the node documentation correctly published https://circleci.com/developer/orbs/orb/cypress-io/cypress?version=dev:98eca619c68c9db6fcff36aa1c92701265a5e76c#usage-node-version . The blocker is the incorrect pnpm implementation.

```yml
version: '2.1'
orbs:
  cypress: cypress-io/cypress@3
jobs:
  run-cypress-in-specified-node-version:
    executor:
      name: cypress/default
      node-version: '20.6'
    steps:
      - cypress/install:
          package-manager: npm
      - cypress/run-tests:
          cypress-command: npx cypress run
          start-command: npm run start:dev
workflows:
  use-my-orb:
    jobs:
      - run-cypress-in-specified-node-version:
          name: Run Cypress in Node 20
```

**Comment by MikeMcC399** [comment]
https://circleci.com/developer/orbs/orb/cypress-io/cypress#usage-node-version now displays:

```yml
version: '2.1'
orbs:
  cypress: cypress-io/cypress@3
jobs:
  run-cypress-in-specified-node-version:
    executor:
      name: cypress/default
      node-version: '20.6'
    steps:
      - cypress/install:
          package-manager: npm
      - cypress/run-tests:
          cypress-command: npx cypress run
          start-command: npm run start:dev
workflows:
  use-my-orb:
    jobs:
      - run-cypress-in-specified-node-version:
          name: Run Cypress in Node 20
```

This issue is now resolved!
