### ISSUE TITLE
Edge example fails - web docs

### ISSUE THREAD

**Issue by MikeMcC399** [cypress-io/circleci-orb#482]
## Issue

The [usage example](https://circleci.com/developer/orbs/orb/cypress-io/cypress#usage-edge) published to the [CircleCI website - cypress-io/cypress@3.3.1](https://circleci.com/developer/orbs/orb/cypress-io/cypress) for running Cypress against the Microsoft Edge web browser using the [Cypress CircleCI Orb](https://circleci.com/developer/orbs/orb/cypress-io/cypress) fails.

There is no Edge browser available, only the default Electron browser bundled with Cypress.

The failing example code is:

```yaml
version: '2.1'
orbs:
  cypress: cypress-io/cypress@3
workflows:
  use-my-orb:
    jobs:
      - cypress/run:
          cypress-command: npx cypress run --browser edge
          start-command: npm run start:dev
```

## Logs

```text
DevTools listening on ws://127.0.0.1:33367/devtools/browser/b3d05bc3-1f27-4c8b-a846-b3991acbfb1f
Can't run because you've entered an invalid browser name.

Browser: edge was not found on your system or is not supported by Cypress.

Cypress supports the following browsers:
 - electron
 - chrome
 - chromium
 - chrome:canary
 - edge
 - firefox

You can also use a custom browser: https://on.cypress.io/customize-browsers

Available browsers found on your system are:
 - electron
Can't run because you've entered an invalid browser name.

Browser: edge was not found on your system or is not supported by Cypress.

Cypress supports the following browsers:
 - electron
 - chrome
 - chromium
 - chrome:canary
 - edge
 - firefox

You can also use a custom browser: https://on.cypress.io/customize-browsers

Available browsers found on your system are:
 - electron

Exited with code exit status 1
```

## Previous issue

- https://github.com/cypress-io/circleci-orb/issues/419
