### ISSUE TITLE
Edge example fails - source code

### ISSUE THREAD

**Issue by MikeMcC399** [cypress-io/circleci-orb#488]
## Issue

The example source code [src/examples/edge.yml](https://github.com/cypress-io/circleci-orb/blob/master/src/examples/edge.yml) in the GitHub [cypress-io/circleci-orb](https://github.com/cypress-io/circleci-orb) repo for running Cypress against the Microsoft Edge web browser using the [Cypress CircleCI Orb](https://circleci.com/developer/orbs/orb/cypress-io/cypress) fails.

- There is no Edge browser available, only the default Electron browser bundled with Cypress. The Cypress Docker image specified in the `executor` is unused. The [cypress/run](https://circleci.com/developer/orbs/orb/cypress-io/cypress#jobs-run) job has no provision for specifying an alternate executor. See https://github.com/cypress-io/circleci-orb/issues/429. It uses the `cimg/node:18.16.1-browsers` image defined in [src/executors/default.yml](https://github.com/cypress-io/circleci-orb/blob/master/src/executors/default.yml).

The failing example source code in [src/examples/edge.yml](https://github.com/cypress-io/circleci-orb/blob/master/src/examples/edge.yml) is:

```yaml
description: >
  Run Cypress tests in Microsoft Edge.
usage:
  version: 2.1
  orbs:
    cypress: cypress-io/cypress@3
  executor:
    docker:
      image: cypress/browsers:node-18.14.1-chrome-111.0.5563.146-1-ff-111.0.1-edge-111.0.1661.54-1
  workflows:
    use-my-orb:
      jobs:
        - cypress/run:
            start-command: "npm run start:dev"
            cypress-command: "npx cypress run --browser edge"
```

The runnable part of this code is

```yml
version: 2.1
orbs:
  cypress: cypress-io/cypress@3
executor:
  docker:
    image: cypress/browsers:node-18.14.1-chrome-111.0.5563.146-1-ff-111.0.1-edge-111.0.1661.54-1
workflows:
  use-my-orb:
    jobs:
      - cypress/run:
          start-command: "npm run start:dev"
          cypress-command: "npx cypress run --browser edge"
```

## Logs

```text
Digest: sha256:49903b71aac206cdc489648589909f480a24f178d3274a2979686377f7fbf88c
Status: Downloaded newer image for cimg/node:18.16.1-browsers
```

```text
DevTools listening on ws://127.0.0.1:33367/devtools/browser/b3d05bc3-1f27-4c8b-a846-b3991acbfb1f
Can't run because you've entered an invalid browser name.

Browser: edge was not found on your system or is not supported by Cypress.

Cypress supports the following browsers:
 - electron
 - chrome
 - chromium
 - chrome:canary
 - edge
 - firefox

You can also use a custom browser: https://on.cypress.io/customize-browsers

Available browsers found on your system are:
 - electron
Can't run because you've entered an invalid browser name.

Browser: edge was not found on your system or is not supported by Cypress.

Cypress supports the following browsers:
 - electron
 - chrome
 - chromium
 - chrome:canary
 - edge
 - firefox

You can also use a custom browser: https://on.cypress.io/customize-browsers

Available browsers found on your system are:
 - electron

Exited with code exit status 1
```

## Other

relates to
- https://github.com/cypress-io/circleci-orb/issues/482
- https://github.com/cypress-io/circleci-orb/issues/419

**Comment by MikeMcC399** [comment]
- PR https://github.com/cypress-io/circleci-orb/pull/489 was not fully successful 🙁 

https://app.circleci.com/pipelines/github/cypress-io/circleci-orb/1974/workflows/6bea899f-82b4-4755-8869-8636dcfed543/jobs/6970

********************************************************************************
Your development orb has been published. It will expire in 30 days.
You can preview what this will look like on the CircleCI Orb Registry at the following link:
https://circleci.com/developer/orbs/orb/cypress-io/cypress?version=dev:fab347ff110b7fe66cf9adeb586d856852174583

https://circleci.com/developer/orbs/orb/cypress-io/cypress?version=dev:fab347ff110b7fe66cf9adeb586d856852174583#usage-edge shows

![image](https://github.com/user-attachments/assets/15758233-94d2-4429-bc7d-d8b2293bbb41)

This does not contain all the workflow lines from https://github.com/cypress-io/circleci-orb/blob/master/src/examples/edge.yml . The `executors` is missing:

```yml
description: >
  Run Cypress tests in Microsoft Edge.
usage:
  version: 2.1
  orbs:
    cypress: cypress-io/cypress@3
  executors:
    cypress-browsers:
      docker:
        - image: cypress/browsers:node-20.17.0-chrome-129.0.6668.70-1-ff-130.0.1-edge-129.0.2792.52-1
  jobs:
    edge-test:
      executor: cypress-browsers
      steps:
        - cypress/install
        - cypress/run-tests:
            start-command: "npm run start:dev"
            cypress-command: 'npx cypress run --browser edge'
  workflows:
    use-my-orb:
      jobs:
        - edge-test
```

I can't see any reason why it would just omit this section, unless this is linked to the Cypress Orb using an outdated version of `orb-tools: circleci/orb-tools@11.6.1`
