### ISSUE TITLE
Missing pnpm v9 and above support

### ISSUE THREAD

**Issue by MikeMcC399** [cypress-io/circleci-orb#495]
## Current behavior

Running Cypress [pnpm](https://pnpm.io/) projects only works out-of-the-box for [pnpm](https://pnpm.io/) `v8` lockfiles. Attempting to run with a [pnpm](https://pnpm.io/) `v9` lockfile causes a fatal error message:

> WARN  Ignoring not compatible lockfile at /home/circleci/project/pnpm-lock.yaml
> ERR_PNPM_NO_LOCKFILE  Cannot install with "frozen-lockfile" because pnpm-lock.yaml is present

## Desired behavior

The Cypress CircleCI orb should support selection and use of any [pnpm](https://pnpm.io/) version `v8`, `v9` and future versions above. pnpm is sensitive to the version of lockfile used.

See also [circleci/node](https://circleci.com/developer/orbs/orb/circleci/node) and [install-pnpm - version](https://circleci.com/developer/orbs/orb/circleci/node#commands-install-pnpm) parameter.

## Test code to reproduce

Run the following workflow against a project with a pnpm lockfile `pnpm-lock.yaml` created with pnpm `v8`, then with `v9`:

- [pnpm@latest-8](https://github.com/pnpm/pnpm/releases/tag/v8.15.9)
- [pnpm@latest-9](https://github.com/pnpm/pnpm/releases/tag/v9.12.3)

using [Cypress CircleCI Orb](https://circleci.com/developer/orbs/orb/cypress-io/cypress):

- [cypress-io/cypress@3.4.0](https://github.com/cypress-io/circleci-orb/releases/tag/v3.4.0) (current `latest`)

```yml
version: 2.1
orbs:
cypress: cypress-io/cypress@3.4.0
workflows:
use-my-orb:
    jobs:
    - cypress/run:
        package-manager: "pnpm"
        start-command: "pnpm start"
        install-command: "pnpm install --frozen-lockfile"
```

## Results

| pnpm version \ Orb version | `3.4.0`  | `lockfileVersion` |
| -------------------------- | -------- | ----------------- |
| `latest-8` (`v8.15.9`)     | Pass     | `6.0`             |
| `latest-9` (`v9.12.3`)     | Fail (1) | `9.0`             |

(1) "WARN  Ignoring not compatible lockfile at /home/circleci/project/pnpm-lock.yaml"

The executor being used is `cimg/node:18.16.1-browsers`, which has `pnpm@8.6.3` pre-installed.

```text
$ docker run --rm --entrypoint sh cimg/node:18.16.1-browsers -c 'pnpm -v'
8.6.3
```
