### ISSUE TITLE
Edge example incorrectly published

### ISSUE THREAD

**Issue by MikeMcC399** [cypress-io/circleci-orb#498]
- Supersedes https://github.com/cypress-io/circleci-orb/issues/488

## Issue

The published [Edge Usage Example](https://circleci.com/developer/orbs/orb/cypress-io/cypress#usage-edge) is incorrect and does not work:

```yml
version: '2.1'
orbs:
  cypress: cypress-io/cypress@3
jobs:
  edge-test:
    executor: cypress-browsers
    steps:
      - cypress/install
      - cypress/run-tests:
          cypress-command: npx cypress run --browser edge
          start-command: npm run start:dev
workflows:
  use-my-orb:
    jobs:
      - edge-test
```

It is missing the `executors` section

```yml
executors:
  cypress-browsers:
    docker:
      - image: cypress/browsers:node-20.17.0-chrome-129.0.6668.70-1-ff-130.0.1-edge-129.0.2792.52-1
```

- This was reported in https://github.com/CircleCI-Public/circleci-cli/issues/1076 on Oct 2, 2024.

## Background

- PR https://github.com/cypress-io/circleci-orb/pull/489 fixed the example source code [src/examples/edge.yml](https://github.com/cypress-io/circleci-orb/blob/master/src/examples/edge.yml) in the GitHub [cypress-io/circleci-orb](https://github.com/cypress-io/circleci-orb) repo for running Cypress against the Microsoft Edge web browser using the [Cypress CircleCI Orb](https://circleci.com/developer/orbs/orb/cypress-io/cypress).

The example source code in [src/examples/edge.yml](https://github.com/cypress-io/circleci-orb/blob/master/src/examples/edge.yml) is:

```yaml
description: >
  Run Cypress tests in Microsoft Edge.
usage:
  version: 2.1
  orbs:
    cypress: cypress-io/cypress@3
  executors:
    cypress-browsers:
      docker:
        - image: cypress/browsers:node-20.17.0-chrome-129.0.6668.70-1-ff-130.0.1-edge-129.0.2792.52-1
  jobs:
    edge-test:
      executor: cypress-browsers
      steps:
        - cypress/install
        - cypress/run-tests:
            start-command: "npm run start:dev"
            cypress-command: 'npx cypress run --browser edge'
  workflows:
    use-my-orb:
      jobs:
        - edge-test
```

The runnable part of this code is

```yml
version: 2.1
orbs:
  cypress: cypress-io/cypress@3
executors:
  cypress-browsers:
    docker:
      - image: cypress/browsers:node-20.17.0-chrome-129.0.6668.70-1-ff-130.0.1-edge-129.0.2792.52-1
jobs:
  edge-test:
    executor: cypress-browsers
    steps:
      - cypress/install
      - cypress/run-tests:
          start-command: "npm run start:dev"
          cypress-command: 'npx cypress run --browser edge'
workflows:
  use-my-orb:
    jobs:
      - edge-test
```

However `circleci orb pack ./src` drops the `executors` section resulting in a non-working workflow.
