### ISSUE TITLE
Install Firefox fails

### ISSUE THREAD

**Issue by ttomaszewski-litify** [cypress-io/circleci-orb#504]
In the last 1 day, "Install Firefox" step fails. We are using `install-browsers: true` in the configuration.

**Comment by abponcio** [comment]
seems like I'm not the only one

<img width="1156" alt="Image" src="https://github.com/user-attachments/assets/600a937b-9e43-4c08-9d8c-020c4fd1eff4" />

Ran it multiple times, but this firefox always fails

**Comment by MikeMcC399** [comment]
@abponcio 

This is due to the issue https://github.com/CircleCI-Public/browser-tools-orb/issues/122.

It requires an update in this repo to https://github.com/CircleCI-Public/browser-tools-orb/releases/tag/v1.5.1, currently using:

https://github.com/cypress-io/circleci-orb/blob/d2c7c66e3ee2c300a97d016f6bc3af2012ca92bf/src/%40orb.yml#L13

- Due to https://github.com/cypress-io/circleci-orb/issues/451 this would best be addressed by a member of the Cypress.io team.

**Comment by ParallelUniv3rse** [comment]
Workaround is to pin the firefox version to v134 or below in your `config.yml` as mentioned [here](https://github.com/CircleCI-Public/browser-tools-orb/issues/122#issuecomment-2634552142)

```
- browser-tools/install-browser-tools:
    firefox-version: "134.0.2" # FIXME: hotfix for firefox install failing from version 135 (https://github.com/cypress-io/circleci-orb/issues/504)
```

**Comment by MikeMcC399** [comment]
```yml
      - cypress/install:
          install-browsers: true
```

now fails in https://github.com/cypress-io/cypress-example-kitchensink

- For example https://github.com/cypress-io/cypress-example-kitchensink/pull/926

**Comment by fathom-alastair** [comment]
@ParallelUniv3rse could you help me figure out where that pinned version directive should sit in our config.yml? 

we're encountering the same problem and i'm not familiar with circleci...

```
version: 2.1

orbs:
  aws-cli: circleci/aws-cli@5.2.0
  node: circleci/node@7.1.0
  slack: circleci/slack@5.1.1
  cypress: cypress-io/cypress@3.4.2

parameters:
  environment:
    type: string
    default: ""
  sandbox:
    type: string
    default: ""

workflows:
  test:
    when:
      and:
        - equal: ["", << pipeline.parameters.environment >>]
        - equal: ["", << pipeline.parameters.sandbox >>]
    jobs:
      - cypress/run:
        install-browsers: true
        cypress-command: "npx cypress run --component --browser chrome"
        filters:
          branches:
            ignore:
              - release
              - main

...snip...
```
