### ISSUE TITLE
add parameter to store test artifacts (screenshots, videos) on CI

### ISSUE THREAD

**Issue by bahmutov** [cypress-io/circleci-orb#52]
Using `store_artifacts` option after run

```
- store_artifacts:
      path: cypress/videos
- store_artifacts:
      path: cypress/screenshots
```
