### ISSUE TITLE
caching key should take OS / executor name into account

### ISSUE THREAD

**Issue by bahmutov** [cypress-io/circleci-orb#56]
To avoid mixing dependencies from different OS. Then we could use same orb to build on Linux and Mac for example, like I am trying in https://github.com/cypress-io/cypress-example-todomvc/pull/80

it would be nice to do this

```yaml
version: 2.1
orbs:
  cypress: cypress-io/cypress@1.2.0

executors:
  mac:
    macos:
      xcode: "10.1.0"

workflows:
  build:
    jobs:
      - cypress/run:
          name: Linux test
      - cypress/run:
          name: Mac test
          executor: mac
```

and get both builds using their own caches. Right now it tries to use Linux cache on Mac https://circleci.com/gh/cypress-io/cypress-example-todomvc/313

```
Found a cache from build 307 at cache-mac-build-79-ipAJGERZllQPwdX7i0NoFA5DdFdL7ktmv7d1IrOvf7w=
Size: 146 MB
Cached paths:
  * /root/.npm
  * /root/.cache

Downloading cache archive...
Validating cache...

Unarchiving cache...
root/.npm/: Failed to create dir 'root'Can't create 'root/.npm'
root/.npm/_cacache/: Failed to create dir 'root'Can't create 'root/.npm/_cacache'
```
