### ISSUE TITLE
Allow custom environment to be set

### ISSUE THREAD

**Issue by Limess** [cypress-io/circleci-orb#58]
On our regular install job for other CI steps, we set:

```PUPPETEER_SKIP_CHROMIUM_DOWNLOAD: 'true'```

to avoid installing chromium for jobs which do not use it, as the install is slow. We instead use the circleci base docker image with Chromium pre-installed.

It'd be nice to be able to set this variable in order to skip this in the cypress install step as well.

**Comment by Limess** [comment]
I've now realised this is possible by passing a custom executor (as needed when using chrome as a browser), e.g:

```yaml

executors:
  cypress-base-chrome69:
    docker:
      - image: cypress/browsers:chrome69
    environment:
      PUPPETEER_SKIP_CHROMIUM_DOWNLOAD: 'true'

workflows:
  build-and-deploy:

      # cypress orb has its own install steps
      - cypress/run:
          executor: cypress-base-chrome69
          browser: 'chrome'
```

however I'll leave this open for discussion as I believe an `environment` parameter would generally be more convenient.
