### ISSUE TITLE
If using Yarn to install dependencies do not cache ~/.npm folder

### ISSUE THREAD

**Issue by bahmutov** [cypress-io/circleci-orb#65]
If we use `npm ci` to install NPM dependencies and Cypress binary we need to cache folders
- `~/.npm`
- `~/.cache`

If we allow `yarn` command to install NPM dependencies we need to only cache folder `~/.cache`

We cannot control the cached folders using a parameter, unfortunately. I would love to say something like this
```
when <parameters.command> eq "npm ci"
  - save_cache:
        key: cache-npm-ci-{{ .Branch }}-{{ checksum "package.json" }}
        paths:
        - ~/.npm
        - ~/.cache
when <parameters.command> eq "yarn"
  - save_cache:
        key: cache-yarn-{{ .Branch }}-{{ checksum "package.json" }}
        paths:
        - ~/.cache  
```

and the right folder would be cached

**Comment by eddiewebb** [comment]
Added in #66 

```
      - when:
          condition: << parameters.yarn >>
          steps:
            - save_cache:
                key: cache-{{ arch }}-{{ .Branch }}-{{ checksum "package.json" }}
                paths:
                  - ~/.cache
      - unless:
          condition: << parameters.yarn >>
          steps:
            - save_cache:
                key: cache-{{ arch }}-{{ .Branch }}-{{ checksum "package.json" }}
                paths:
                  - ~/.npm
                  - ~/.cache
```
