### ISSUE TITLE
Set NPM Auth Token?

### ISSUE THREAD

**Issue by nmchaves** [cypress-io/circleci-orb#67]
I'm new to CircleCI, and I'm trying to use the Cypress CircleCI Orb. To build my application, I need to install private NPM packages (using Yarn). So I need to be able to run a command like this somewhere in `config.yml`:
```sh
echo "//registry.npmjs.org/:_authToken=${NPM_TOKEN}" > ~/.npmrc
```

I don't know where to put it though. The `install` job's `build` parameter runs _after_ `yarn install`. Is it possible to set the NPM auth token somewhere? Maybe @eddiewebb would have a suggestion? I think one approach would be to add a parameter called `pre` to the `install` job.

Alternatively, I'd imagine I could write out my `config.yml` with all the settings I need (except for the NPM token). Then, I could "eject" using `circleci config process config.yml` and figure out where to add the NPM auth token.

#### Side Note

This Orb seems _really_ cool! We've been using the Cypress Dashboard and Travis CI to run our Cypress tests in CI for the past several months. We never found a way to avoid installing Cypress on every machine when running the tests in parallel. That introduces a huge bottleneck. We could run our test suite _so_ much more efficiently with this orb!

**Comment by nmchaves** [comment]
@eddiewebb thanks so much 🙏:pray: !! We're able to set the auth token and install our private packages now! We're just facing 1 challenge: we can't get Cypress to connect to our application. Here's our `config.yml`:
```yml
version: 2.1
orbs:
  cypress: cypress-io/cypress@1.4.0
workflows:
  build:
    jobs:
      - cypress/install:
          yarn: true
          # Build the application and store the static assets in the build directory
          build: yarn build
          pre-steps:
            - run: echo "//registry.npmjs.org/:_authToken=${NPM_TOKEN}" > ~/.npmrc
      - cypress/run:
          yarn: true
          pre-steps:
            - run: echo "//registry.npmjs.org/:_authToken=${NPM_TOKEN}" > ~/.npmrc
          requires:
            - cypress/install
          # Run the application (using the static assets in the build directory)
          start: "serve -p 3000 build"
          wait-on: "http://localhost:3000"
```

The `cypress/run` job is running the application at `http://localhost:3000`. However, the "wait-on" times out after 10 minutes. 

If I remove the `wait-on`, all of the Cypress tests fail (because they can't connect to the application). In this case, the error messages are all like:
```
CypressError: cy.visit() failed trying to load:

http://localhost:3000/login

The response we received from your web server was:

  > 404: Not Found
```

During `cyress/install` job, we create a `build` directory with all of the static assets needed to run our application. It seems like the `build` directory isn't getting carried over to the `cyress/run` job (which would explain those 404 errors). Do we need to run another command to make sure the `build` directory can be accessed during the `cypress/run` job?

**Comment by eddiewebb** [comment]
I would just drop the first job, and the run job will install too. Just pass your build command to the run job.

Is there a reason you want 2 jobs?

**Comment by nmchaves** [comment]
I was hoping to take care of the "overhead" (and possibly run our unit tests) during the first job. That way, we'd get more benefit from increasing the parallelism in the 2nd job. But it isn't strictly necessary. Anyways, everything seems to be running very quickly on CircleCI. I'll try removing the first job.

**Comment by eddiewebb** [comment]
That's a fair use case.

You can add `cypress/write_workspace` as a `post-steps` on your first job to pass everything built in the project directory on to the next job. 

I think the second job will still try to install Cypress, but you can skip the building and unit testing.

**Comment by bahmutov** [comment]
@nmchaves I would always strive to avoid duplicate work. So I would install NPM dependencies and build the server in the `cypress/install` job, then it will attach the workspace and pass everything into `cypress/run` jobs (which can run in parallel). The example https://github.com/cypress-io/circleci-orb/blob/master/docs/examples.md#build-app shows this

But you can also just look at the effective config, either on CircleCI web application or using CLI command https://github.com/cypress-io/circleci-orb#effective-config to see what exactly is going on.

To close this issue I will add an example of setting NPM auth token using `pre-` job step like @eddiewebb has shown to the documentation, it is a good one.

**Comment by nmchaves** [comment]
Thank you both so much for the help! We got this working earlier today thanks to your advice. I'm blown away how by how faster our build runs now. We're going to be able to reduce our build time by ~65% without even paying more than we paid on Travis. Amazing! 

@eddiewebb congrats on getting a new, happy customer 🎉 
and @bahmutov congrats on making an existing Cypress customer even more satisfied 😎   

In case someone reads this issue later, the `cypress/install` job _does_ persist our `build` directory correctly so that it can be accessed during the `cypress/run` job. The 404 error was caused by me failing to pass a `-s` flag to `serve`. Here's a simplified version of our `config.yml`:
```
version: 2.1
orbs:
  cypress: cypress-io/cypress@1.4.0
workflows:
  build:
    jobs:
      - cypress/install:
          yarn: true
          pre-steps:
            - run: echo "//registry.npmjs.org/:_authToken=${NPM_TOKEN}" > ~/.npmrc
          build: yarn build
      - cypress/run:
          requires:
            - cypress/install
          start: yarn serve -s -p 3000 build
          wait-on: "http://localhost:3000"
          spec: "cypress/integration/**/*_spec.ts"
          record: true
          parallel: true
          parallelism: 3
          group: "all tests"
```
