### ISSUE TITLE
Grouping is not included under your current billing plan.

### ISSUE THREAD

**Issue by leogoesger** [cypress-io/circleci-orb#79]
Here is our circle ci set up. The error I am getting using a starter plan is about grouping. I thought that was fixed in previous PRs, but it is still showing up.
```
workflows:
  version: 2.1
  build_and_deploy_staging:
    jobs:
      - build
      - deploy-staging:
          requires:
            - build
          filters:
            branches:
              only: master

      - cypress/run:
          record: true
          parallel: false
          requires:
            - deploy-staging
          filters:
            branches:
              only: master
```
