### ISSUE TITLE
npm ci: executable not accessible from cypress

### ISSUE THREAD

**Issue by leogoesger** [cypress-io/circleci-orb#82]
```
version: 2.1
orbs:
  # import Cypress orb by specifying an exact version
  cypress: cypress-io/cypress@1.5.0

workflows:
  version: 2.1
  build_and_deploy_staging:
    jobs:
      - build
      - deploy-staging:
          requires:
            - build
          filters:
            branches:
              only: master

      - cypress/run:
          record: true
          parallel: false
          requires:
            - deploy-staging
          filters:
            branches:
              only: master
```

This is weird, the CI has stopped working using the yml in circleCI. Do i need to change where to store the cache?

**Comment by bahmutov** [comment]
I don't know what has stopped working. Where are you installing Cypress and other NPM dependencies? See our parallel example - cypress/run should depend on cypress/install job, if you use your custom `build` job, it needs to work the same way as `cypress/install`

**Comment by leogoesger** [comment]
```version: 2.1
orbs:
  # import Cypress orb by specifying an exact version
  cypress: cypress-io/cypress@1.5.0
jobs:
  build:
    docker:
      # specify the version you desire here
      - image: circleci/node:10.8.0

    working_directory: ~/repo

    steps:
      - checkout

      - run: npm install

      - run:
          name: Run test
          command: npm test -- --coverage

      - run:
          name: Send codecov coverage report
          command: bash <(curl -s https://codecov.io/bash) -f coverage/lcov.info -t

  deploy-staging:
    docker:
      - image: circleci/node:10.8.0-browsers

    working_directory: ~/repo

    steps:
      - checkout

      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "package.json" }}
            # fallback to using the latest cache if no exact match is found
            - v1-dependencies-

      - run: npm install

      - save_cache:
          paths:
            - node_modules
          key: v1-dependencies-{{ checksum "package.json" }}

      - add_ssh_keys:
          fingerprints:
            - '83:3a:18:5a:b2:de:84:a7:32:77:71:d1:da:1a:2e:2d'

      - run: npm run build

      - run:
          name: copy over scp
          command: |
            scp -o StrictHostKeyChecking=no -r build/* foodnome@68.183.172.144:/var/www/foodnome.com/html
            scp -o StrictHostKeyChecking=no -r ./robots.txt foodnome@68.183.172.144:/var/www/foodnome.com/html
            scp -o StrictHostKeyChecking=no -r ./sitemap.xml foodnome@68.183.172.144:/var/www/foodnome.com/html

      - run:
          name: Rebuild and Start
          command: |
            ssh -o StrictHostKeyChecking=no foodnome@68.183.172.144 \<<EOF 
              cd foodnome-api
              npm run stage:prepare
              exit
            EOF

workflows:
  version: 2.1
  build_and_deploy_staging:
    jobs:
      - build
      - deploy-staging:
          requires:
            - build
          filters:
            branches:
              only: master

      - cypress/run:
          record: true
          parallel: false
          requires:
            - deploy-staging
          filters:
            branches:
              only: master
```

**Comment by leogoesger** [comment]
this is what i have so far. Do you see any errors?

**Comment by leogoesger** [comment]
I even tried it with just this....
```
# to use orbs, must use version >= 2.1
version: 2.1
orbs:
  # import Cypress orb by specifying an exact version x.y.z
  # or the latest version 1.x.x using "@1" syntax
  cypress: cypress-io/cypress@1
workflows:
  build:
    jobs:
      # "cypress" is the name of the imported orb
      # "run" is the name of the job defined in Cypress orb
      - cypress/run
```

And it still does not work
