### ISSUE TITLE
Is this the optimal config for my statically generated Nuxt app?

### ISSUE THREAD

**Issue by mornir** [cypress-io/circleci-orb#83]
Hi!

I'm currently using this config and it works:
```yml
version: 2.1
orbs:
  cypress: cypress-io/cypress@1
workflows:
  build:
    jobs:
      - cypress/run:
          executor: cypress/browsers-chrome69
          browser: chrome
          start: npm run serve
          wait-on: 'http://localhost:8080'
```
However, since I'm building the app as a statically generated website with the `nuxt generate` command, I wanted to first generate all the HTML pages and then launch a server from the dist folder, something like this:

```yml
version: 2.1
orbs:
  cypress: cypress-io/cypress@1
workflows:
  build:
    jobs:
      - cypress/install:
          build: 'npm run generate'
      - cypress/run:
          requires:
            - cypress/install
          executor: cypress/browsers-chrome69
          browser: chrome
           # using npm package live-server
          start: 'cd dist && live-server'
```
But this doesn't work. Should I stick with the working config above?
Here a link to the repo: https://github.com/mornir/copywork-portfolio
