### ISSUE TITLE
Wrong Cypress cache folder is saved on Mac

### ISSUE THREAD

**Issue by bahmutov** [cypress-io/circleci-orb#98]
When running on Mac executor, we should be caching folder like
```
$ npx cypress cache path
/Users/gleb/Library/Caches/Cypress
```
Instead we cache `~/.cache` folder, just like on Linux

Thus if we split a Mac workflow into `install` + `run` jobs, the `run` job cannot find the binary

See the problem in workflow https://circleci.com/workflow-run/7de9dbf3-42ec-4965-a998-571e4b4c7f4a

```
#!/bin/bash -eo pipefail
npx cypress run \
   \
   \
   --record \
     --group 'Mac build'  \
     --parallel  \
^D^DThe cypress npm package is installed, but the Cypress binary is missing.

We expected the binary to be installed here: /Users/distiller/Library/Caches/Cypress/3.2.0/Cypress.app/Contents/MacOS/Cypress

Reasons it may be missing:

- You're caching 'node_modules' but are not caching this path: /Users/distiller/Library/Caches/Cypress
- You ran 'npm install' at an earlier build step but did not persist: /Users/distiller/Library/Caches/Cypress

Properly caching the binary will fix this error and avoid downloading and unzipping Cypress.

Alternatively, you can run 'cypress install' to download the binary again.

https://on.cypress.io/not-installed-ci-error
----------

Platform: darwin (17.7.0)
Cypress Version: 3.2.0
Exited with code 1
```

When attaching workspace, we can see how small it is - because it does not include the Cypress binary

```
Downloading workspace layers
  workflows/workspaces/7de9dbf3-42ec-4965-a998-571e4b4c7f4a/0/b02a2a44-1c84-4f1f-961d-09adc2ed8c96/0/108.tar.gz - 32 MB
Applying workspace layers
  b02a2a44-1c84-4f1f-961d-09adc2ed8c96
```

Workaround: on Mac use just a single `cypress/run` job

**Comment by bahmutov** [comment]
Same for cache
```
- run:
        name: Npm CI
        command: npm ci
    - run:
        command: npx cypress verify
    - save_cache:
        key: cache-{{ arch }}-{{ .Branch }}-{{ checksum "package.json" }}
        paths:
        - ~/.npm
        - ~/.cache
    - run:
        command: npm run build
    - persist_to_workspace:
        root: ~/
        paths:
        - project
        - .cache/Cypress
```

**Comment by bahmutov** [comment]
The only workaround for now is to use a Mac executor with an absolute path like `CYPRESS_CACHE_FOLDER: /Users/distiller/.cache/Cypress`

```
executors:
  mac:
    macos:
      xcode: "10.1.0"
    environment:
      CYPRESS_CACHE_FOLDER: /Users/distiller/.cache/Cypress
```
